// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Invitation is one not yet accepted.
 */
export class Invitation {
    "id": string;
    "email": string;
    "role": string;
    "projects"?: { [_ in string]?: string };
    "expiresAt": number;

    /** Creates a new Invitation instance. */
    constructor($$source: Partial<Invitation> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("email" in $$source)) {
            this["email"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("expiresAt" in $$source)) {
            this["expiresAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Invitation instance from a string or object.
     */
    static createFrom($$source: any = {}): Invitation {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("projects" in $$parsedSource) {
            $$parsedSource["projects"] = $$createField3_0($$parsedSource["projects"]);
        }
        return new Invitation($$parsedSource as Partial<Invitation>);
    }
}

/**
 * Member is a person in a hosted team.
 */
export class Member {
    "userId": string;
    "memberId": string;
    "name": string;
    "email": string;
    "role": string;

    /**
     * a collaborator's
     */
    "projects"?: { [_ in string]?: string };

    /** Creates a new Member instance. */
    constructor($$source: Partial<Member> = {}) {
        if (!("userId" in $$source)) {
            this["userId"] = "";
        }
        if (!("memberId" in $$source)) {
            this["memberId"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("email" in $$source)) {
            this["email"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Member instance from a string or object.
     */
    static createFrom($$source: any = {}): Member {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("projects" in $$parsedSource) {
            $$parsedSource["projects"] = $$createField5_0($$parsedSource["projects"]);
        }
        return new Member($$parsedSource as Partial<Member>);
    }
}

/**
 * Project is a project of the team as the caller may reach it.
 */
export class Project {
    "id": string;
    "name": string;

    /**
     * read, write
     */
    "access": string;

    /** Creates a new Project instance. */
    constructor($$source: Partial<Project> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("access" in $$source)) {
            this["access"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Project instance from a string or object.
     */
    static createFrom($$source: any = {}): Project {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Project($$parsedSource as Partial<Project>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
