// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Applied is a preset in use for a folder ("" is the project folder).
 */
export class Applied {
    "folder": string;
    "preset": string;

    /**
     * no .r3v.yaml: found from the folder
     */
    "detected": boolean;

    /** Creates a new Applied instance. */
    constructor($$source: Partial<Applied> = {}) {
        if (!("folder" in $$source)) {
            this["folder"] = "";
        }
        if (!("preset" in $$source)) {
            this["preset"] = "";
        }
        if (!("detected" in $$source)) {
            this["detected"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Applied instance from a string or object.
     */
    static createFrom($$source: any = {}): Applied {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Applied($$parsedSource as Partial<Applied>);
    }
}

/**
 * PresetEntry is a line of presets:.
 */
export class PresetEntry {
    /**
     * "" the project folder
     */
    "folder": string;
    "preset": string;

    /**
     * R3V wrote it from what it found
     */
    "found": boolean;

    /** Creates a new PresetEntry instance. */
    constructor($$source: Partial<PresetEntry> = {}) {
        if (!("folder" in $$source)) {
            this["folder"] = "";
        }
        if (!("preset" in $$source)) {
            this["preset"] = "";
        }
        if (!("found" in $$source)) {
            this["found"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PresetEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): PresetEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PresetEntry($$parsedSource as Partial<PresetEntry>);
    }
}
