// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Estimate is what moving a team means, before anything is done.
 */
export class Estimate {
    "projects": EstimateProject[];

    /**
     * bytes R3V Cloud will keep
     */
    "hosted": number;

    /**
     * bytes the team's storage holds now
     */
    "storage": number;
    "people": number;

    /**
     * Where the team's storage is (for making the read-only key): its
     * address, bucket, folder; "r2", "aws" or "" for another.
     */
    "endpoint": string;
    "bucket": string;
    "folder": string;
    "provider": string;

    /** Creates a new Estimate instance. */
    constructor($$source: Partial<Estimate> = {}) {
        if (!("projects" in $$source)) {
            this["projects"] = [];
        }
        if (!("hosted" in $$source)) {
            this["hosted"] = 0;
        }
        if (!("storage" in $$source)) {
            this["storage"] = 0;
        }
        if (!("people" in $$source)) {
            this["people"] = 0;
        }
        if (!("endpoint" in $$source)) {
            this["endpoint"] = "";
        }
        if (!("bucket" in $$source)) {
            this["bucket"] = "";
        }
        if (!("folder" in $$source)) {
            this["folder"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Estimate instance from a string or object.
     */
    static createFrom($$source: any = {}): Estimate {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("projects" in $$parsedSource) {
            $$parsedSource["projects"] = $$createField0_0($$parsedSource["projects"]);
        }
        return new Estimate($$parsedSource as Partial<Estimate>);
    }
}

/**
 * EstimateProject is one project's part.
 */
export class EstimateProject {
    "id": string;
    "name": string;
    "versions": number;
    "bytes": number;

    /** Creates a new EstimateProject instance. */
    constructor($$source: Partial<EstimateProject> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("versions" in $$source)) {
            this["versions"] = 0;
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EstimateProject instance from a string or object.
     */
    static createFrom($$source: any = {}): EstimateProject {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EstimateProject($$parsedSource as Partial<EstimateProject>);
    }
}

/**
 * State is how a team's move goes.
 */
export class State {
    /**
     * "" (none), "copying", "finishing", "done"
     */
    "phase": string;

    /**
     * the hosted team's id
     */
    "to": string;
    "items": number;
    "itemsDone": number;
    "bytes": number;
    "bytesDone": number;

    /**
     * the service copied all it was given
     */
    "copied": boolean;
    "failed": number;
    "error": string;

    /** Creates a new State instance. */
    constructor($$source: Partial<State> = {}) {
        if (!("phase" in $$source)) {
            this["phase"] = "";
        }
        if (!("to" in $$source)) {
            this["to"] = "";
        }
        if (!("items" in $$source)) {
            this["items"] = 0;
        }
        if (!("itemsDone" in $$source)) {
            this["itemsDone"] = 0;
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }
        if (!("bytesDone" in $$source)) {
            this["bytesDone"] = 0;
        }
        if (!("copied" in $$source)) {
            this["copied"] = false;
        }
        if (!("failed" in $$source)) {
            this["failed"] = 0;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new State instance from a string or object.
     */
    static createFrom($$source: any = {}): State {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new State($$parsedSource as Partial<State>);
    }
}

// Private type creation functions
const $$createType0 = EstimateProject.createFrom;
const $$createType1 = $Create.Array($$createType0);
