// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * TrackEdit is one piece of unsaved work: a track (or a set-wide setting)
 * changed since the version the workspace is on.
 */
export class TrackEdit {
    "set": string;

    /**
     * empty for set-wide changes
     */
    "track_id"?: string;
    "name": string;

    /**
     * "added" | "removed" | "modified"
     */
    "change": string;

    /** Creates a new TrackEdit instance. */
    constructor($$source: Partial<TrackEdit> = {}) {
        if (!("set" in $$source)) {
            this["set"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("change" in $$source)) {
            this["change"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrackEdit instance from a string or object.
     */
    static createFrom($$source: any = {}): TrackEdit {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TrackEdit($$parsedSource as Partial<TrackEdit>);
    }
}
