// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Hunk is a run of changes with up to context unchanged lines around it.
 */
export class Hunk {
    "lines": Line[];

    /** Creates a new Hunk instance. */
    constructor($$source: Partial<Hunk> = {}) {
        if (!("lines" in $$source)) {
            this["lines"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Hunk instance from a string or object.
     */
    static createFrom($$source: any = {}): Hunk {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lines" in $$parsedSource) {
            $$parsedSource["lines"] = $$createField0_0($$parsedSource["lines"]);
        }
        return new Hunk($$parsedSource as Partial<Hunk>);
    }
}

/**
 * Line is one line of a hunk. Old and New count from 1 (0: not on that side).
 */
export class Line {
    /**
     * same | add | del
     */
    "kind": string;
    "old": number;
    "new": number;
    "text": string;

    /** Creates a new Line instance. */
    constructor($$source: Partial<Line> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("old" in $$source)) {
            this["old"] = 0;
        }
        if (!("new" in $$source)) {
            this["new"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Line instance from a string or object.
     */
    static createFrom($$source: any = {}): Line {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Line($$parsedSource as Partial<Line>);
    }
}

// Private type creation functions
const $$createType0 = Line.createFrom;
const $$createType1 = $Create.Array($$createType0);
