// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Capabilities are features a backend offers beyond versions; the app shows
 * what goes with them only when the team's backend has them.
 */
export class Capabilities {
    /**
     * files can be locked for editing
     */
    "locks": boolean;

    /**
     * who is working on what, live
     */
    "presence": boolean;

    /** Creates a new Capabilities instance. */
    constructor($$source: Partial<Capabilities> = {}) {
        if (!("locks" in $$source)) {
            this["locks"] = false;
        }
        if (!("presence" in $$source)) {
            this["presence"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Capabilities instance from a string or object.
     */
    static createFrom($$source: any = {}): Capabilities {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Capabilities($$parsedSource as Partial<Capabilities>);
    }
}

/**
 * Member is a person in the team. Versions record the member's id, so a new
 * display name applies to everything they did.
 */
export type Member = any;

/**
 * Storage is team storage (an S3-compatible bucket) as a person fills it in.
 */
export class Storage {
    /**
     * Endpoint: the S3 API address, e.g. https://<account>.r2.cloudflarestorage.com
     * (a Cloudflare account id alone works too; a trailing /<bucket> is taken
     * as the bucket).
     */
    "endpoint": string;
    "bucket": string;

    /**
     * inside the bucket; "" means "r3v"
     */
    "folder": string;

    /**
     * "" means "auto" (R2)
     */
    "region": string;
    "accessKey": string;
    "secretKey": string;

    /** Creates a new Storage instance. */
    constructor($$source: Partial<Storage> = {}) {
        if (!("endpoint" in $$source)) {
            this["endpoint"] = "";
        }
        if (!("bucket" in $$source)) {
            this["bucket"] = "";
        }
        if (!("folder" in $$source)) {
            this["folder"] = "";
        }
        if (!("region" in $$source)) {
            this["region"] = "";
        }
        if (!("accessKey" in $$source)) {
            this["accessKey"] = "";
        }
        if (!("secretKey" in $$source)) {
            this["secretKey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Storage instance from a string or object.
     */
    static createFrom($$source: any = {}): Storage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Storage($$parsedSource as Partial<Storage>);
    }
}
