// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Install is a Live installed here.
 */
export class Install {
    /**
     * "Ableton Live 12 Suite"
     */
    "name": string;

    /**
     * "12.3.2" ("" when unknown)
     */
    "version": string;

    /**
     * "Suite", "Standard", "Intro", "Lite" ("" when unknown)
     */
    "edition": string;

    /**
     * its folder
     */
    "path": string;

    /** Creates a new Install instance. */
    constructor($$source: Partial<Install> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("edition" in $$source)) {
            this["edition"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Install instance from a string or object.
     */
    static createFrom($$source: any = {}): Install {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Install($$parsedSource as Partial<Install>);
    }
}
