// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Info describes a sample.
 */
export class Info {
    "rate": number;
    "channels": number;

    /**
     * 0 for compressed formats
     */
    "bits": number;
    "seconds": number;

    /** Creates a new Info instance. */
    constructor($$source: Partial<Info> = {}) {
        if (!("rate" in $$source)) {
            this["rate"] = 0;
        }
        if (!("channels" in $$source)) {
            this["channels"] = 0;
        }
        if (!("bits" in $$source)) {
            this["bits"] = 0;
        }
        if (!("seconds" in $$source)) {
            this["seconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Info instance from a string or object.
     */
    static createFrom($$source: any = {}): Info {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Info($$parsedSource as Partial<Info>);
    }
}

/**
 * Result is what a conversion will write, with notes on what the format
 * forces (e.g. "MP3 goes up to 48 kHz: 96 kHz becomes 48 kHz").
 */
export class Result {
    "rate": number;
    "channels": number;
    "bits": number;

    /**
     * kbps, for lossy formats
     */
    "bitrate": number;
    "notes": string[];

    /** Creates a new Result instance. */
    constructor($$source: Partial<Result> = {}) {
        if (!("rate" in $$source)) {
            this["rate"] = 0;
        }
        if (!("channels" in $$source)) {
            this["channels"] = 0;
        }
        if (!("bits" in $$source)) {
            this["bits"] = 0;
        }
        if (!("bitrate" in $$source)) {
            this["bitrate"] = 0;
        }
        if (!("notes" in $$source)) {
            this["notes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     */
    static createFrom($$source: any = {}): Result {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("notes" in $$parsedSource) {
            $$parsedSource["notes"] = $$createField4_0($$parsedSource["notes"]);
        }
        return new Result($$parsedSource as Partial<Result>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
