// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as liveenv$0 from "../liveenv/models.js";

/**
 * LiveReport is about the project's Live Sets.
 */
export class LiveReport {
    "sets": SetLine[];

    /**
     * Needs: the newest Live version that saved one of the sets.
     */
    "needs": string;
    "installed": liveenv$0.Install[];

    /**
     * Opens: "yes" (this computer's newest Live is as new as Needs),
     * "older" (it is older: Live can't open sets saved by a newer Live),
     * "none" (no Live found here).
     */
    "opens": string;
    "samples": SampleReport;
    "plugins": PluginLine[];

    /**
     * PluginsKnown: Live's plugin list could be read (else Here is
     * "unknown" for every plugin).
     */
    "pluginsKnown": boolean;

    /** Creates a new LiveReport instance. */
    constructor($$source: Partial<LiveReport> = {}) {
        if (!("sets" in $$source)) {
            this["sets"] = [];
        }
        if (!("needs" in $$source)) {
            this["needs"] = "";
        }
        if (!("installed" in $$source)) {
            this["installed"] = [];
        }
        if (!("opens" in $$source)) {
            this["opens"] = "";
        }
        if (!("samples" in $$source)) {
            this["samples"] = (new SampleReport());
        }
        if (!("plugins" in $$source)) {
            this["plugins"] = [];
        }
        if (!("pluginsKnown" in $$source)) {
            this["pluginsKnown"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LiveReport instance from a string or object.
     */
    static createFrom($$source: any = {}): LiveReport {
        const $$createField0_0 = $$createType1;
        const $$createField2_0 = $$createType3;
        const $$createField4_0 = $$createType4;
        const $$createField5_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sets" in $$parsedSource) {
            $$parsedSource["sets"] = $$createField0_0($$parsedSource["sets"]);
        }
        if ("installed" in $$parsedSource) {
            $$parsedSource["installed"] = $$createField2_0($$parsedSource["installed"]);
        }
        if ("samples" in $$parsedSource) {
            $$parsedSource["samples"] = $$createField4_0($$parsedSource["samples"]);
        }
        if ("plugins" in $$parsedSource) {
            $$parsedSource["plugins"] = $$createField5_0($$parsedSource["plugins"]);
        }
        return new LiveReport($$parsedSource as Partial<LiveReport>);
    }
}

/**
 * MemberCheck is a teammate's computer against the project, from the setup
 * they shared.
 */
export class MemberCheck {
    "name": string;
    "updated": string;

    /**
     * their newest Live ("" none)
     */
    "live": string;

    /**
     * "yes", "older", "none" (see LiveReport)
     */
    "opens": string;

    /**
     * MissingPlugins: plugins the sets use that their Live didn't find;
     * OtherVersions: plugins they have in another version than this computer.
     */
    "missingPlugins": string[];
    "otherVersions": PluginVersion[];
    "missingPacks": string[];
    "pluginsKnown": boolean;
    "packsKnown": boolean;

    /** Creates a new MemberCheck instance. */
    constructor($$source: Partial<MemberCheck> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("updated" in $$source)) {
            this["updated"] = "";
        }
        if (!("live" in $$source)) {
            this["live"] = "";
        }
        if (!("opens" in $$source)) {
            this["opens"] = "";
        }
        if (!("missingPlugins" in $$source)) {
            this["missingPlugins"] = [];
        }
        if (!("otherVersions" in $$source)) {
            this["otherVersions"] = [];
        }
        if (!("missingPacks" in $$source)) {
            this["missingPacks"] = [];
        }
        if (!("pluginsKnown" in $$source)) {
            this["pluginsKnown"] = false;
        }
        if (!("packsKnown" in $$source)) {
            this["packsKnown"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MemberCheck instance from a string or object.
     */
    static createFrom($$source: any = {}): MemberCheck {
        const $$createField4_0 = $$createType7;
        const $$createField5_0 = $$createType9;
        const $$createField6_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("missingPlugins" in $$parsedSource) {
            $$parsedSource["missingPlugins"] = $$createField4_0($$parsedSource["missingPlugins"]);
        }
        if ("otherVersions" in $$parsedSource) {
            $$parsedSource["otherVersions"] = $$createField5_0($$parsedSource["otherVersions"]);
        }
        if ("missingPacks" in $$parsedSource) {
            $$parsedSource["missingPacks"] = $$createField6_0($$parsedSource["missingPacks"]);
        }
        return new MemberCheck($$parsedSource as Partial<MemberCheck>);
    }
}

/**
 * PackLine is a pack the sets use; Here: "yes", "no" or "unknown".
 */
export class PackLine {
    "name": string;
    "here": string;

    /** Creates a new PackLine instance. */
    constructor($$source: Partial<PackLine> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("here" in $$source)) {
            this["here"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PackLine instance from a string or object.
     */
    static createFrom($$source: any = {}): PackLine {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PackLine($$parsedSource as Partial<PackLine>);
    }
}

/**
 * PluginLine is a third-party plugin the sets use.
 */
export class PluginLine {
    "name": string;
    "format": string;
    "sets": string[];

    /**
     * Here: "yes" (Live found it on this computer), "no", or "unknown".
     */
    "here": string;

    /**
     * from Live's list, when here
     */
    "vendor": string;

    /**
     * the version here
     */
    "version": string;

    /** Creates a new PluginLine instance. */
    constructor($$source: Partial<PluginLine> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("format" in $$source)) {
            this["format"] = "";
        }
        if (!("sets" in $$source)) {
            this["sets"] = [];
        }
        if (!("here" in $$source)) {
            this["here"] = "";
        }
        if (!("vendor" in $$source)) {
            this["vendor"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginLine instance from a string or object.
     */
    static createFrom($$source: any = {}): PluginLine {
        const $$createField2_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sets" in $$parsedSource) {
            $$parsedSource["sets"] = $$createField2_0($$parsedSource["sets"]);
        }
        return new PluginLine($$parsedSource as Partial<PluginLine>);
    }
}

/**
 * PluginVersion is a plugin in two versions: theirs and this computer's.
 */
export class PluginVersion {
    "name": string;
    "theirs": string;
    "here": string;

    /** Creates a new PluginVersion instance. */
    constructor($$source: Partial<PluginVersion> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("theirs" in $$source)) {
            this["theirs"] = "";
        }
        if (!("here" in $$source)) {
            this["here"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginVersion instance from a string or object.
     */
    static createFrom($$source: any = {}): PluginVersion {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PluginVersion($$parsedSource as Partial<PluginVersion>);
    }
}

/**
 * Report is a project's check.
 */
export class Report {
    /**
     * tracked: what a first version uploads
     */
    "files": number;
    "bytes": number;

    /**
     * left out by the rules
     */
    "ignored": number;
    "ignoredBytes": number;

    /**
     * nil: no Live Sets
     */
    "live": LiveReport | null;

    /**
     * Team: teammates who share their setup, checked against the project
     * (nil when not known: no team, or its storage can't keep setups).
     */
    "team": MemberCheck[];

    /**
     * TeamSetups: the team can keep setups; ShareSetup: this computer's
     * is shared.
     */
    "teamSetups": boolean;
    "shareSetup": boolean;

    /** Creates a new Report instance. */
    constructor($$source: Partial<Report> = {}) {
        if (!("files" in $$source)) {
            this["files"] = 0;
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }
        if (!("ignored" in $$source)) {
            this["ignored"] = 0;
        }
        if (!("ignoredBytes" in $$source)) {
            this["ignoredBytes"] = 0;
        }
        if (!("live" in $$source)) {
            this["live"] = null;
        }
        if (!("team" in $$source)) {
            this["team"] = [];
        }
        if (!("teamSetups" in $$source)) {
            this["teamSetups"] = false;
        }
        if (!("shareSetup" in $$source)) {
            this["shareSetup"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Report instance from a string or object.
     */
    static createFrom($$source: any = {}): Report {
        const $$createField4_0 = $$createType11;
        const $$createField5_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("live" in $$parsedSource) {
            $$parsedSource["live"] = $$createField4_0($$parsedSource["live"]);
        }
        if ("team" in $$parsedSource) {
            $$parsedSource["team"] = $$createField5_0($$parsedSource["team"]);
        }
        return new Report($$parsedSource as Partial<Report>);
    }
}

/**
 * SampleReport counts the samples the sets use.
 */
export class SampleReport {
    "inProject": number;

    /**
     * outside the project: kept with the versions
     */
    "external": number;
    "externalBytes": number;

    /**
     * from packs: each computer needs the pack
     */
    "packRefs": number;
    "packs": PackLine[];

    /**
     * not found: saved as missing
     */
    "missing": string[];

    /**
     * Restorable: missing samples R3V has a copy of (it can bring them
     * back into the project).
     */
    "restorable": number;

    /** Creates a new SampleReport instance. */
    constructor($$source: Partial<SampleReport> = {}) {
        if (!("inProject" in $$source)) {
            this["inProject"] = 0;
        }
        if (!("external" in $$source)) {
            this["external"] = 0;
        }
        if (!("externalBytes" in $$source)) {
            this["externalBytes"] = 0;
        }
        if (!("packRefs" in $$source)) {
            this["packRefs"] = 0;
        }
        if (!("packs" in $$source)) {
            this["packs"] = [];
        }
        if (!("missing" in $$source)) {
            this["missing"] = [];
        }
        if (!("restorable" in $$source)) {
            this["restorable"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SampleReport instance from a string or object.
     */
    static createFrom($$source: any = {}): SampleReport {
        const $$createField4_0 = $$createType15;
        const $$createField5_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("packs" in $$parsedSource) {
            $$parsedSource["packs"] = $$createField4_0($$parsedSource["packs"]);
        }
        if ("missing" in $$parsedSource) {
            $$parsedSource["missing"] = $$createField5_0($$parsedSource["missing"]);
        }
        return new SampleReport($$parsedSource as Partial<SampleReport>);
    }
}

/**
 * SetLine is one set.
 */
export class SetLine {
    "path": string;
    "version": string;
    "err": string;

    /** Creates a new SetLine instance. */
    constructor($$source: Partial<SetLine> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("err" in $$source)) {
            this["err"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SetLine instance from a string or object.
     */
    static createFrom($$source: any = {}): SetLine {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SetLine($$parsedSource as Partial<SetLine>);
    }
}

// Private type creation functions
const $$createType0 = SetLine.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = liveenv$0.Install.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = SampleReport.createFrom;
const $$createType5 = PluginLine.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Array($Create.Any);
const $$createType8 = PluginVersion.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = LiveReport.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = MemberCheck.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = PackLine.createFrom;
const $$createType15 = $Create.Array($$createType14);
