// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the service the frontend calls. Every method that touches a project
 * takes its folder (root) and holds that project's lock, so the background
 * team watch and user actions never run at the same time.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as convert$0 from "../internal/convert/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as health$0 from "../internal/health/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as remote$0 from "../internal/remote/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as teammove$0 from "../internal/teammove/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddIgnoreRule adds `- ignore: pattern` at the end of the rules in the
 * project's .r3v.yaml (creating the file): the last rule wins. The file
 * is committed with the project, so the rule is the team's once shared.
 */
export function AddIgnoreRule(root: string, pattern: string): $CancellablePromise<void> {
    return $Call.ByID(871931324, root, pattern);
}

/**
 * AddMilestone names version for the whole team.
 */
export function AddMilestone(root: string, version: string, name: string, note: string): $CancellablePromise<void> {
    return $Call.ByID(1857537538, root, version, name, note);
}

/**
 * AddProjectToTeam starts tracking an Ableton project folder as part of a
 * team. It returns quickly; the frontend then commits and uploads the first
 * version with Save, showing its progress.
 */
export function AddProjectToTeam(teamID: string, folder: string): $CancellablePromise<$models.TeamProject> {
    return $Call.ByID(1639873693, teamID, folder).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AllProjects lists every team's projects as this computer knows them,
 * without asking the teams (no network): the ones here, and the rest as
 * each team last listed them (the quick launcher looks across teams).
 */
export function AllProjects(): $CancellablePromise<$models.TeamProjects[]> {
    return $Call.ByID(2502170346).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ArchiveBranches archives branches (a branch and those made from it: not
 * main, not the one you are on); keep: those made from them that stay,
 * each with the branch it now comes from. They can be got back
 * (UnarchiveBranch).
 */
export function ArchiveBranches(root: string, keys: string[], keep: { [_ in string]?: string }): $CancellablePromise<void> {
    return $Call.ByID(319459245, root, keys, keep);
}

/**
 * ArchivedBranches lists project root's archived branches, the last
 * archived first.
 */
export function ArchivedBranches(root: string): $CancellablePromise<$models.ArchivedBranch[]> {
    return $Call.ByID(3626916479, root).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * AutoUpdate: updates install on their own (when R3V is in the tray with
 * nothing to do, or quits); on by default.
 */
export function AutoUpdate(): $CancellablePromise<boolean> {
    return $Call.ByID(563883155);
}

/**
 * Autostart reports whether R3V starts when the user signs in to Windows.
 */
export function Autostart(): $CancellablePromise<boolean> {
    return $Call.ByID(3395223714);
}

/**
 * BackUpNow starts a backup of team teamID now.
 */
export function BackUpNow(teamID: string): $CancellablePromise<void> {
    return $Call.ByID(2406360797, teamID);
}

/**
 * BackupInfo says how team teamID is backed up.
 */
export function BackupInfo(teamID: string): $CancellablePromise<$models.BackupInfo | null> {
    return $Call.ByID(883742151, teamID).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * BackupOthers says how team teamID's other members back it up.
 */
export function BackupOthers(teamID: string): $CancellablePromise<$models.BackupOthers | null> {
    return $Call.ByID(2803914964, teamID).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * BackupReminder: whether to suggest setting up a backup of team teamID:
 * a storage team in use for a while (settled), nobody has backed up lately,
 * not put off this week.
 */
export function BackupReminder(teamID: string): $CancellablePromise<boolean> {
    return $Call.ByID(1070858433, teamID);
}

/**
 * BackupStorage is this computer's backup storage for team teamID, to edit
 * (nil when it backs up to a folder, or not at all).
 */
export function BackupStorage(teamID: string): $CancellablePromise<remote$0.Storage | null> {
    return $Call.ByID(2386159232, teamID).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * BranchList lists project root's branches with their names and colours,
 * from what the team said last (asking it when it hasn't yet).
 */
export function BranchList(root: string): $CancellablePromise<$models.BranchList | null> {
    return $Call.ByID(3264460773, root).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * BreakLock frees someone else's lock (admins; the service checks).
 */
export function BreakLock(root: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(3554492347, root, path);
}

/**
 * BringParked brings changes parked at a place (branch, at: an older
 * version, or "" for its latest) into the project where it is, merged with
 * what's here; uncommitted. Conflicts come back as decisions (call again
 * with resolutions); nothing changes until then.
 */
export function BringParked(root: string, branch: string, at: string, resolutions: { [_ in string]?: string }, force: boolean): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(3835368762, root, branch, at, resolutions, force).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * BringSamplesIn puts samples into the project (Samples/Imported, or back at
 * their place) and points the sets at them: missing ones R3V has a copy
 * of, and/or those only in .r3v. It rewrites sets, so not while one is
 * open in Live (unless force). Result.Log holds how many.
 */
export function BringSamplesIn(root: string, missing: boolean, kept: boolean, force: boolean): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(1487897253, root, missing, kept, force).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * Busy: a project is in the middle of something (a commit, an upload, a
 * download): no update is installed now.
 */
export function Busy(): $CancellablePromise<boolean> {
    return $Call.ByID(2059138868);
}

/**
 * CancelSave stops root's commit or share under way, if it can still stop
 * (false when there is none).
 */
export function CancelSave(root: string): $CancellablePromise<boolean> {
    return $Call.ByID(238831226, root);
}

/**
 * CancelTeamMove gives a move up (not once it's done).
 */
export function CancelTeamMove(teamID: string): $CancellablePromise<void> {
    return $Call.ByID(3570406171, teamID);
}

/**
 * Channel says which release line this is and which one updates come from.
 */
export function Channel(): $CancellablePromise<$models.ChannelInfo> {
    return $Call.ByID(3873166424).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * CheckUpdate asks for a newer release (at most every 6 hours) and returns
 * it, or nil when this is the newest. A signed one is downloaded right away,
 * in the background. R3V_NO_UPDATE_CHECK=1 turns it off;
 * R3V_DEV_VERSION pretends to be another version and R3V_DEV_FEED
 * checks another feed (testing).
 */
export function CheckUpdate(): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByID(3266594098).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * CheckUpdateNow asks for a newer release now (the settings' "Check for
 * updates"), not waiting for the next check.
 */
export function CheckUpdateNow(): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByID(1278125058).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * ChooseFolder asks the user for a folder ("" when cancelled).
 */
export function ChooseFolder(title: string): $CancellablePromise<string> {
    return $Call.ByID(2466102992, title);
}

/**
 * CleanUpStorage finds files in a team's storage that no version of any
 * project uses; with remove it deletes those found unused at least a day
 * before (and not written in the last week). See remote.CollectGarbage.
 */
export function CleanUpStorage(teamID: string, remove: boolean): $CancellablePromise<$models.StorageCleanup | null> {
    return $Call.ByID(3277129484, teamID, remove).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * CloudCancelSignIn stops waiting for the browser.
 */
export function CloudCancelSignIn(): $CancellablePromise<void> {
    return $Call.ByID(1860802338);
}

/**
 * CloudCreateTeam makes a hosted team (you its owner) and selects it.
 */
export function CloudCreateTeam(name: string): $CancellablePromise<$models.TeamSummary> {
    return $Call.ByID(179761727, name).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * CloudInvitationInfo reads an invitation link (nothing accepted).
 */
export function CloudInvitationInfo(link: string): $CancellablePromise<$models.CloudInvitation | null> {
    return $Call.ByID(513957193, link).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * CloudInvite emails someone a link to join (collaborators: with the
 * projects they reach, id -> "read" or "write").
 */
export function CloudInvite(teamID: string, email: string, role: string, projects: { [_ in string]?: string }): $CancellablePromise<void> {
    return $Call.ByID(2979409107, teamID, email, role, projects);
}

/**
 * CloudJoin joins the team an invitation link is for and selects it.
 */
export function CloudJoin(link: string): $CancellablePromise<$models.TeamSummary> {
    return $Call.ByID(3803091886, link).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * CloudJoinAs joins the team an invitation link is for as who one was in
 * it before it moved to R3V Cloud (claim: their member id; "" for someone
 * new), and selects it.
 */
export function CloudJoinAs(link: string, claim: string): $CancellablePromise<$models.TeamSummary> {
    return $Call.ByID(3740839370, link, claim).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * CloudPeople reads a hosted team's people, pending invitations and
 * projects.
 */
export function CloudPeople(teamID: string): $CancellablePromise<$models.CloudPeople> {
    return $Call.ByID(769827489, teamID).then(($result: any) => {
        return $$createType23($result);
    });
}

/**
 * CloudRemoveMember takes someone out of the team.
 */
export function CloudRemoveMember(teamID: string, userID: string): $CancellablePromise<void> {
    return $Call.ByID(1780221200, teamID, userID);
}

/**
 * CloudSetAccess gives a collaborator a project ("read", "write") or takes
 * it away ("").
 */
export function CloudSetAccess(teamID: string, projectID: string, userID: string, access: string): $CancellablePromise<void> {
    return $Call.ByID(3494513076, teamID, projectID, userID, access);
}

export function CloudSetRole(teamID: string, userID: string, role: string): $CancellablePromise<void> {
    return $Call.ByID(799668818, teamID, userID, role);
}

/**
 * CloudSignIn signs in through the browser and adds the account's teams to
 * the team list. It waits until the person is done in the browser (or
 * CloudCancelSignIn).
 */
export function CloudSignIn(): $CancellablePromise<$models.CloudStatus> {
    return $Call.ByID(2541945236).then(($result: any) => {
        return $$createType24($result);
    });
}

/**
 * CloudSignOut signs this computer out; hosted teams stay listed, signed out.
 */
export function CloudSignOut(): $CancellablePromise<void> {
    return $Call.ByID(3989479105);
}

/**
 * CloudStatus says whether this build offers R3V-Cloud and who is signed
 * in (asking the service only when signed in).
 */
export function CloudStatus(): $CancellablePromise<$models.CloudStatus> {
    return $Call.ByID(454267468).then(($result: any) => {
        return $$createType24($result);
    });
}

export function CloudWithdraw(teamID: string, invitationID: string): $CancellablePromise<void> {
    return $Call.ByID(3007263000, teamID, invitationID);
}

/**
 * CommitWarnings runs the project's pre-commit checks (e.g. a Unity asset
 * without its .meta) on what would be committed; the page shows them first.
 */
export function CommitWarnings(root: string): $CancellablePromise<string[]> {
    return $Call.ByID(4067198037, root).then(($result: any) => {
        return $$createType25($result);
    });
}

/**
 * ConnectTeam adds a team (its connection code) and makes it the current one.
 */
export function ConnectTeam(address: string): $CancellablePromise<$models.TeamSummary> {
    return $Call.ByID(1429027116, address).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * ConvertFile writes a sample in another format next to it and returns the
 * new file's path. Progress comes as "progress" events (stage "converting").
 */
export function ConvertFile(root: string, file: string, format: string, kbps: number, rate: number, channels: number, bits: number): $CancellablePromise<string> {
    return $Call.ByID(2776427410, root, file, format, kbps, rate, channels, bits);
}

export function ConvertFormats(): $CancellablePromise<$models.ConvertFormat[]> {
    return $Call.ByID(2412184076).then(($result: any) => {
        return $$createType27($result);
    });
}

/**
 * ConvertInfo describes a sample (rate, channels, bits, length).
 */
export function ConvertInfo(root: string, file: string): $CancellablePromise<convert$0.Info> {
    return $Call.ByID(1037866264, root, file).then(($result: any) => {
        return $$createType28($result);
    });
}

/**
 * ConvertPlan tells what a conversion would write, with notes on what the
 * format forces. kbps: 0 for the default; rate, channels, bits: 0 keeps the
 * original's.
 */
export function ConvertPlan(root: string, file: string, format: string, kbps: number, rate: number, channels: number, bits: number): $CancellablePromise<convert$0.Result> {
    return $Call.ByID(1645260407, root, file, format, kbps, rate, channels, bits).then(($result: any) => {
        return $$createType29($result);
    });
}

/**
 * ConvertTarget is the file a conversion would write (relative path).
 */
export function ConvertTarget(root: string, file: string, format: string): $CancellablePromise<string> {
    return $Call.ByID(2728181197, root, file, format);
}

/**
 * CopyIntoProject copies files and folders (absolute paths, e.g. dropped
 * from Explorer) into dir, a folder of the project ("" its top). When a name
 * is already there nothing is copied and Clashes lists them.
 */
export function CopyIntoProject(root: string, dir: string, sources: string[]): $CancellablePromise<$models.DropResult | null> {
    return $Call.ByID(719724195, root, dir, sources).then(($result: any) => {
        return $$createType31($result);
    });
}

/**
 * CreateBranch starts a branch called name (any text where the team keeps
 * branch records) with color (a palette number, "" for the app's pick), and
 * switches to it when switchTo is set. It returns the branch's key.
 */
export function CreateBranch(root: string, name: string, color: string, switchTo: boolean): $CancellablePromise<string> {
    return $Call.ByID(779167049, root, name, color, switchTo);
}

/**
 * CreateStorageTeam sets up a team on storage (e.g. a Cloudflare R2 bucket):
 * it checks the bucket and keys work, names the team (unless the bucket
 * already holds a named team) and connects this computer to it. The
 * connection code for teammates comes from TeamConnectionCode.
 */
export function CreateStorageTeam(s: remote$0.Storage, name: string): $CancellablePromise<$models.TeamSummary> {
    return $Call.ByID(2232560939, s, name).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * DeleteBranch deletes archived branch key for good (listed no more).
 */
export function DeleteBranch(root: string, key: string): $CancellablePromise<void> {
    return $Call.ByID(1841045814, root, key);
}

/**
 * DeleteProjectFromTeam removes a project from the team's storage for
 * everyone. The copy on this computer (if any) is kept, with its history, as
 * a project on this computer only.
 */
export function DeleteProjectFromTeam(teamID: string, projectID: string): $CancellablePromise<void> {
    return $Call.ByID(3285807394, teamID, projectID);
}

/**
 * DiscardAll drops every uncommitted change: the project folder goes back to
 * the version it is on.
 */
export function DiscardAll(root: string, force: boolean): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(1207794436, root, force).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * DiscardAndUpdate drops uncommitted changes and takes the team's latest
 * versions of this branch.
 */
export function DiscardAndUpdate(root: string, resolutions: { [_ in string]?: string }, force: boolean): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(2616406255, root, resolutions, force).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * DiscardFile puts one file back as it is in the version the project is on;
 * from: where a moved file was (it goes back there).
 */
export function DiscardFile(root: string, file: string, $from: string, force: boolean): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(2604499587, root, file, $from, force).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * DiscardFiles puts some changed files back as they are in the version the
 * project is on (a moved file goes back where it was too).
 */
export function DiscardFiles(root: string, files: string[], force: boolean): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(1372921808, root, files, force).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * DiscardParked drops changes parked at a place: they are gone.
 */
export function DiscardParked(root: string, branch: string, at: string): $CancellablePromise<void> {
    return $Call.ByID(2853190608, root, branch, at);
}

/**
 * DismissLocksOffer: the team's admin said no to turning locks on (not
 * offered again).
 */
export function DismissLocksOffer(teamID: string): $CancellablePromise<void> {
    return $Call.ByID(2285771913, teamID);
}

/**
 * DownloadProject downloads a team project into parent/<name> Project.
 */
export function DownloadProject(teamID: string, projectID: string, parent: string): $CancellablePromise<$models.TeamProject> {
    return $Call.ByID(3618682278, teamID, projectID, parent).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DownloadUpdate fetches the newer release's installer and checks its
 * signature; "update" events say how it goes.
 */
export function DownloadUpdate(): $CancellablePromise<void> {
    return $Call.ByID(1591394060);
}

/**
 * EditMilestone renames milestone id and changes its note.
 */
export function EditMilestone(root: string, id: string, name: string, note: string): $CancellablePromise<void> {
    return $Call.ByID(1674524029, root, id, name, note);
}

/**
 * Edition names a build with extensions ("" for the public app).
 */
export function Edition(): $CancellablePromise<string> {
    return $Call.ByID(1687242285);
}

/**
 * EstimateTeamMove plans every project of team teamID (reading its
 * versions: a while for a long history) and says what moving means.
 */
export function EstimateTeamMove(teamID: string): $CancellablePromise<$models.TeamMoveEstimate | null> {
    return $Call.ByID(4108271007, teamID).then(($result: any) => {
        return $$createType33($result);
    });
}

/**
 * ExportVersion writes a version as a separate project folder inside parent
 * and returns its path.
 */
export function ExportVersion(root: string, id: string, parent: string): $CancellablePromise<string> {
    return $Call.ByID(1739963593, root, id, parent);
}

/**
 * FileDiff describes how a set changed between two versions ("" for from:
 * the set was added), as diff lines.
 */
export function FileDiff(root: string, file: string, $from: string, to: string): $CancellablePromise<string[]> {
    return $Call.ByID(3174793948, root, file, $from, to).then(($result: any) => {
        return $$createType25($result);
    });
}

/**
 * FileHistory lists the versions of the current branch that changed path.
 */
export function FileHistory(root: string, file: string): $CancellablePromise<$models.FileVersion[]> {
    return $Call.ByID(942713033, root, file).then(($result: any) => {
        return $$createType35($result);
    });
}

/**
 * FinishTeamMove freezes the old team, sends what was shared since, and,
 * once all of it is copied, finishes (in the background).
 */
export function FinishTeamMove(teamID: string): $CancellablePromise<void> {
    return $Call.ByID(354692814, teamID);
}

/**
 * FollowMovedTeam is for a teammate: their team moved to R3V Cloud and
 * they joined it there (toID); their projects of the old team follow.
 */
export function FollowMovedTeam(fromID: string, toID: string): $CancellablePromise<void> {
    return $Call.ByID(656987622, fromID, toID);
}

/**
 * ForgetProject removes a project from the list (the folder is untouched).
 */
export function ForgetProject(root: string): $CancellablePromise<void> {
    return $Call.ByID(298910517, root);
}

/**
 * GoToVersion puts the project folder in the state of a version ("latest"
 * goes back to the newest). discard drops uncommitted changes; force goes
 * ahead while Live is running.
 */
export function GoToVersion(root: string, id: string, discard: boolean, force: boolean): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(86002254, root, id, discard, force).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * HistoryDownloadSize is how much the files of older versions that are only
 * in the team's storage weigh, for one project (root) or for every project
 * of a team (teamID), to offer downloading them when leaving the team.
 */
export function HistoryDownloadSize(root: string, teamID: string): $CancellablePromise<number> {
    return $Call.ByID(2070559902, root, teamID);
}

/**
 * HushBackupReminder puts the reminder off for a week.
 */
export function HushBackupReminder(teamID: string): $CancellablePromise<void> {
    return $Call.ByID(78931545, teamID);
}

/**
 * IgnoreOptions are the rules offered for leaving a file or folder out:
 * just it, or all like it (same extension, or folders of that name).
 */
export function IgnoreOptions(rel: string, isDir: boolean): $CancellablePromise<$models.IgnoreOption[]> {
    return $Call.ByID(2209390107, rel, isDir).then(($result: any) => {
        return $$createType37($result);
    });
}

/**
 * InstallUpdate installs the downloaded update: its installer runs on its
 * own, replaces R3V and opens it again; R3V quits.
 */
export function InstallUpdate(): $CancellablePromise<void> {
    return $Call.ByID(2500909893);
}

/**
 * KeepThisVersion continues from the older version the project is on: it
 * becomes a new version on top of the latest (shared with the team).
 */
export function KeepThisVersion(root: string, message: string, resolutions: { [_ in string]?: string }): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(2098169356, root, message, resolutions).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * LastChanges tells, for each file in the version the project is on, the
 * newest version that changed it (along the branch's first parents), for
 * the Files tab's "last change".
 */
export function LastChanges(root: string): $CancellablePromise<{ [_ in string]?: $models.Version }> {
    return $Call.ByID(1895063018, root).then(($result: any) => {
        return $$createType39($result);
    });
}

/**
 * LocalOverview is Overview without asking the team (no network): what the
 * app shows at once while Overview asks it, which can take a while when the
 * team can't be reached.
 */
export function LocalOverview(): $CancellablePromise<$models.Overview | null> {
    return $Call.ByID(2575697031).then(($result: any) => {
        return $$createType41($result);
    });
}

/**
 * LocateProject points a team project at a folder that was moved.
 */
export function LocateProject(teamID: string, projectID: string, folder: string): $CancellablePromise<$models.TeamProject> {
    return $Call.ByID(682923240, teamID, projectID, folder).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * LockFiles locks files, or folders (a path ending in "/": everything in
 * it, files added later too).
 */
export function LockFiles(root: string, paths: string[]): $CancellablePromise<$models.LockOutcome | null> {
    return $Call.ByID(1165788305, root, paths).then(($result: any) => {
        return $$createType43($result);
    });
}

/**
 * MemberLooks maps the members of a project's team to how they show (none
 * for a team that keeps no looks: the app shows initials).
 */
export function MemberLooks(root: string): $CancellablePromise<{ [_ in string]?: $models.MemberLook }> {
    return $Call.ByID(2774060677, root).then(($result: any) => {
        return $$createType45($result);
    });
}

export function MergeBranch(root: string, name: string, message: string, resolutions: { [_ in string]?: string }, force: boolean): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(3015301699, root, name, message, resolutions, force).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * MergeVersion merges a version into the current branch; message describes
 * the merge version ("" for the default, see Preview.Message).
 */
export function MergeVersion(root: string, id: string, message: string, resolutions: { [_ in string]?: string }, force: boolean): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(1659313061, root, id, message, resolutions, force).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * MoveProject moves project root to team teamID (copy: copies it, the
 * project staying in its team): its whole history goes straight from one
 * team's storage to the other's (see project.MoveToTeam), with the
 * project's progress; CancelSave stops it (what was copied stays unseen
 * on the other team, and moving again goes on from there). The files here
 * are untouched.
 */
export function MoveProject(root: string, teamID: string, copy: boolean): $CancellablePromise<void> {
    return $Call.ByID(1170826645, root, teamID, copy);
}

/**
 * OpenInLive opens a set with its default application (Ableton Live).
 */
export function OpenInLive(root: string, $set: string): $CancellablePromise<void> {
    return $Call.ByID(3169931076, root, $set);
}

/**
 * OpenInTool opens one of State.Openable in the project's tool: with the
 * preset's opener, or the file's own program.
 */
export function OpenInTool(root: string, rel: string): $CancellablePromise<void> {
    return $Call.ByID(232784544, root, rel);
}

/**
 * OpenRules opens the project's .r3v.yaml in a text editor (written with
 * what R3V finds first, when missing).
 */
export function OpenRules(root: string): $CancellablePromise<void> {
    return $Call.ByID(818218360, root);
}

/**
 * OpenURL opens a page the app links to in the browser: R3V's (release
 * notes, installer, guides), the update feed's site, Cloudflare's dashboard
 * and docs (team setup). Other addresses are refused.
 */
export function OpenURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(2821011958, url);
}

/**
 * Overview is everything the sidebar and onboarding need.
 */
export function Overview(): $CancellablePromise<$models.Overview | null> {
    return $Call.ByID(3728537718).then(($result: any) => {
        return $$createType41($result);
    });
}

/**
 * PauseBackup stops (or restarts) the daily backups of team teamID.
 */
export function PauseBackup(teamID: string, paused: boolean): $CancellablePromise<void> {
    return $Call.ByID(4211829059, teamID, paused);
}

/**
 * PlanUndo says what undoing version id would do: with a new version, or
 * by taking it back.
 */
export function PlanUndo(root: string, id: string): $CancellablePromise<$models.UndoPlan | null> {
    return $Call.ByID(1416768396, root, id).then(($result: any) => {
        return $$createType47($result);
    });
}

/**
 * Preuploads lists the files going up in the background now.
 */
export function Preuploads(): $CancellablePromise<$models.Preupload[]> {
    return $Call.ByID(2295120844).then(($result: any) => {
        return $$createType49($result);
    });
}

export function PreviewMerge(root: string, name: string): $CancellablePromise<$models.Preview | null> {
    return $Call.ByID(1796516665, root, name).then(($result: any) => {
        return $$createType51($result);
    });
}

/**
 * PreviewMergeVersion previews merging any version (e.g. one in the middle
 * of another branch) into the current branch.
 */
export function PreviewMergeVersion(root: string, id: string): $CancellablePromise<$models.Preview | null> {
    return $Call.ByID(1744263203, root, id).then(($result: any) => {
        return $$createType51($result);
    });
}

export function PreviewUpdate(root: string): $CancellablePromise<$models.Preview | null> {
    return $Call.ByID(3840067402, root).then(($result: any) => {
        return $$createType51($result);
    });
}

/**
 * Profile returns the user's name and look.
 */
export function Profile(): $CancellablePromise<$models.Profile> {
    return $Call.ByID(784333506).then(($result: any) => {
        return $$createType52($result);
    });
}

/**
 * ProjectCheck looks at a project and this computer: for Live Sets, the
 * Live version they need, their samples, plugins and packs, and whether
 * this computer has them; and what a first version uploads. Read only.
 */
export function ProjectCheck(root: string): $CancellablePromise<health$0.Report | null> {
    return $Call.ByID(1553370922, root).then(($result: any) => {
        return $$createType54($result);
    });
}

/**
 * ProjectDownloadSize reads the size of a team project's latest version.
 */
export function ProjectDownloadSize(teamID: string, projectID: string): $CancellablePromise<$models.DownloadSize> {
    return $Call.ByID(2063948083, teamID, projectID).then(($result: any) => {
        return $$createType55($result);
    });
}

/**
 * ProjectFiles lists the changed files; with all, every tracked file in the
 * project folder (not those the rules leave out).
 */
export function ProjectFiles(root: string, all: boolean): $CancellablePromise<$models.ProjectFile[]> {
    return $Call.ByID(3273687165, root, all).then(($result: any) => {
        return $$createType57($result);
    });
}

/**
 * ProjectInfo reads a project folder's name, tool and rules.
 */
export function ProjectInfo(root: string): $CancellablePromise<$models.ProjectInfo | null> {
    return $Call.ByID(4284337826, root).then(($result: any) => {
        return $$createType59($result);
    });
}

/**
 * ProjectLocks reads a project's file locks (On false when it has none).
 */
export function ProjectLocks(root: string): $CancellablePromise<$models.LocksView | null> {
    return $Call.ByID(4291324562, root).then(($result: any) => {
        return $$createType61($result);
    });
}

/**
 * ProjectRules reads a project's rules for the Rules window (writing the
 * file first, when missing).
 */
export function ProjectRules(root: string): $CancellablePromise<$models.RulesDetail | null> {
    return $Call.ByID(3455333517, root).then(($result: any) => {
        return $$createType63($result);
    });
}

/**
 * ReconnectProjects puts Local projects back in their team (see
 * TeamProjectsHere).
 */
export function ReconnectProjects(teamID: string, roots: string[]): $CancellablePromise<void> {
    return $Call.ByID(3241849112, teamID, roots);
}

/**
 * RecoverSwitch puts the files back as the version the project is on, after
 * a switch that stopped halfway (State.Unfinished).
 */
export function RecoverSwitch(root: string, force: boolean): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(1111973759, root, force).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * RemoveMilestone takes milestone id away (its version stays).
 */
export function RemoveMilestone(root: string, id: string): $CancellablePromise<void> {
    return $Call.ByID(1998094825, root, id);
}

/**
 * RemoveRule removes the index-th rule of the project's .r3v.yaml.
 */
export function RemoveRule(root: string, index: number): $CancellablePromise<void> {
    return $Call.ByID(54436055, root, index);
}

/**
 * RemoveTeam disconnects this computer from a team. With keepProjects its
 * downloaded projects move to Local (their versions stay, and they can be
 * committed to here or reconnected later); otherwise they are no longer
 * listed. With fullHistory the files of older versions that are only in the
 * team's storage are downloaded first. Project folders always stay on disk.
 */
export function RemoveTeam(id: string, keepProjects: boolean, fullHistory: boolean): $CancellablePromise<void> {
    return $Call.ByID(25161632, id, keepProjects, fullHistory);
}

/**
 * RenameFile renames a file or folder of the project (rel, relative to
 * root) to name, in the same folder, and returns its new relative path.
 */
export function RenameFile(root: string, rel: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(1679648993, root, rel, name);
}

/**
 * RenameProject gives a project another name, in R3V and for its team;
 * the folder keeps its own. root: the folder when the project is here (""
 * for one only on the team: teamID and projectID say which).
 */
export function RenameProject(teamID: string, projectID: string, root: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(3495244748, teamID, projectID, root, name);
}

export function RenameTeam(id: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(3350230542, id, name);
}

/**
 * RenameTeamForEveryone changes the team's own name, in its storage; every
 * member's R3V follows it.
 */
export function RenameTeamForEveryone(id: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(1253921592, id, name);
}

/**
 * Restore brings back from a backup what team teamID's storage lacks (see
 * RestorePlan), never overwriting anything; it returns how many files it
 * copied.
 */
export function Restore(teamID: string, $from: $models.RestoreSource, run: string): $CancellablePromise<number> {
    return $Call.ByID(603269381, teamID, $from, run);
}

/**
 * RestoreFileVersion puts one file back as it was in a version; the rest of
 * the project stays. The result is an uncommitted change. source: the file's
 * path in that version, when it had another ("" for file).
 */
export function RestoreFileVersion(root: string, file: string, version: string, source: string, force: boolean): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(1588691613, root, file, version, source, force).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * RestorePlan says what restoring a backup (see RestoreSource) as of run
 * ("": the latest) would bring back into team teamID's storage.
 */
export function RestorePlan(teamID: string, $from: $models.RestoreSource, run: string): $CancellablePromise<$models.RestorePlan | null> {
    return $Call.ByID(1280551794, teamID, $from, run).then(($result: any) => {
        return $$createType65($result);
    });
}

/**
 * RulesAt reads a project's rules file in a version (a version id, "" for
 * the project folder now, "none" for no file); file is where it was then
 * ("" for .r3v.yaml).
 */
export function RulesAt(root: string, file: string, version: string): $CancellablePromise<$models.RulesState | null> {
    return $Call.ByID(461881737, root, file, version).then(($result: any) => {
        return $$createType67($result);
    });
}

/**
 * RulesFolder lists a folder of the project (rel; "" the project folder)
 * with whether each file and folder is tracked, and why.
 */
export function RulesFolder(root: string, rel: string): $CancellablePromise<$models.RuleNode[]> {
    return $Call.ByID(3677650056, root, rel).then(($result: any) => {
        return $$createType69($result);
    });
}

/**
 * SampleSpots lists the samples of the project's sets that are missing or
 * only in .r3v. Reads only: no lock.
 */
export function SampleSpots(root: string): $CancellablePromise<$models.SampleSpot[]> {
    return $Call.ByID(3744615968, root).then(($result: any) => {
        return $$createType71($result);
    });
}

/**
 * Save records a version and shares it (merging the team's versions first).
 * 
 * combine: when teammates committed on this branch in the meantime, their
 * versions are combined with this one. Without it such a save changes
 * nothing and returns action "behind", so the user decides (combine, new
 * branch, or discard) with a preview.
 * Save commits (and shares) the changes; paths, when not empty, are the
 * changes to commit: the others stay uncommitted.
 */
export function Save(root: string, message: string, combine: boolean, resolutions: { [_ in string]?: string }, force: boolean, paths: string[]): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(3731647140, root, message, combine, resolutions, force, paths).then(($result: any) => {
        return $$createType14($result);
    });
}

export function SelectTeam(id: string): $CancellablePromise<void> {
    return $Call.ByID(2344488600, id);
}

export function SetAuthor(name: string): $CancellablePromise<void> {
    return $Call.ByID(4039455528, name);
}

export function SetAutoUpdate(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(1364654325, on);
}

/**
 * SetAutostart turns starting R3V at sign-in on or off.
 */
export function SetAutostart(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(1050603160, on);
}

/**
 * SetBackupFolder makes folder where this computer backs up team teamID,
 * and starts a backup. The problem ("" when none) is why the folder can't
 * be used: "other-team" (it holds another team's backup), "not-empty".
 */
export function SetBackupFolder(teamID: string, folder: string): $CancellablePromise<string> {
    return $Call.ByID(1295545445, teamID, folder);
}

/**
 * SetBackupStorage makes S3-compatible storage (another bucket, or a folder
 * of one) where this computer backs up team teamID, and starts a backup.
 * Problems as SetBackupFolder's, and "same-storage": it is (in) the team's
 * own storage.
 */
export function SetBackupStorage(teamID: string, s: remote$0.Storage): $CancellablePromise<string> {
    return $Call.ByID(3048238990, teamID, s);
}

/**
 * SetBranchRecord renames branch key and sets its colour, for the whole
 * team.
 */
export function SetBranchRecord(root: string, key: string, name: string, color: string): $CancellablePromise<void> {
    return $Call.ByID(1863952718, root, key, name, color);
}

/**
 * SetChannel picks where updates come from, and checks there now. To
 * Nightly, its latest build is offered right away; back to Stable, this
 * Nightly stays until a Stable release is newer than it.
 */
export function SetChannel(channel: string): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByID(3355643782, channel).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * SetIdentity sets who this computer is in a team: an existing member
 * (memberID, e.g. the same person on another computer) or a new one
 * (memberID ""). The name goes to the team's member list, so everyone sees
 * it on all of that member's versions, old ones included.
 */
export function SetIdentity(teamID: string, memberID: string, name: string): $CancellablePromise<$models.TeamSummary> {
    return $Call.ByID(3997952233, teamID, memberID, name).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * SetOverview reads a set in a version ("" for the project folder now,
 * "none" for no set) and, unless fromVersion is "none", compares it with
 * the set in fromVersion (at fromFile when it was elsewhere, "" for file).
 */
export function SetOverview(root: string, file: string, version: string, fromFile: string, fromVersion: string): $CancellablePromise<$models.SetView | null> {
    return $Call.ByID(1348533648, root, file, version, fromFile, fromVersion).then(($result: any) => {
        return $$createType73($result);
    });
}

/**
 * SetPreset says which preset applies to a folder of a project ("none": it
 * isn't a project of that tool), in its .r3v.yaml.
 */
export function SetPreset(root: string, folder: string, preset: string): $CancellablePromise<void> {
    return $Call.ByID(865765760, root, folder, preset);
}

/**
 * SetPreupload turns the background upload of big files on or off for
 * team teamID on this computer.
 */
export function SetPreupload(teamID: string, on: boolean): $CancellablePromise<void> {
    return $Call.ByID(3373868385, teamID, on);
}

/**
 * SetProfileColor sets the user's colour (a palette name) for all their
 * teams.
 */
export function SetProfileColor(color: string): $CancellablePromise<$models.Profile> {
    return $Call.ByID(1122390847, color).then(($result: any) => {
        return $$createType52($result);
    });
}

/**
 * SetProfilePicture sets the user's picture (a data: URL of a small square
 * PNG or JPEG; "" for none) for all their teams.
 */
export function SetProfilePicture(url: string): $CancellablePromise<$models.Profile> {
    return $Call.ByID(2377589578, url).then(($result: any) => {
        return $$createType52($result);
    });
}

/**
 * SetProjectLook sets a team project's icon and colour (names) for the
 * whole team.
 */
export function SetProjectLook(teamID: string, projectID: string, icon: string, color: string): $CancellablePromise<void> {
    return $Call.ByID(3818119039, teamID, projectID, icon, color);
}

/**
 * SetShareSetup turns sharing this computer's setup with a team on (it is
 * shared now) or off (the shared one is deleted).
 */
export function SetShareSetup(teamID: string, on: boolean): $CancellablePromise<void> {
    return $Call.ByID(4228162187, teamID, on);
}

/**
 * SetTeamLocks turns file locking on or off for the team and picks the
 * kinds of file that lock by themselves (admins). On, R3Vs without locks
 * must update before sharing.
 */
export function SetTeamLocks(teamID: string, on: boolean, kinds: string[]): $CancellablePromise<void> {
    return $Call.ByID(1834461926, teamID, on, kinds);
}

/**
 * SetTracked tracks a file or folder of the project, or leaves it out, with
 * the fewest rules: a rule of the window's that said the opposite goes; a
 * rule is added only when still needed.
 */
export function SetTracked(root: string, rel: string, dir: boolean, tracked: boolean): $CancellablePromise<void> {
    return $Call.ByID(479997703, root, rel, dir, tracked);
}

/**
 * ShareVersions shares the versions committed here with the project's team
 * without committing the files (a project added to a team, shared later).
 */
export function ShareVersions(root: string): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(900709089, root).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * ShowFile opens Explorer with the file selected.
 */
export function ShowFile(root: string, file: string): $CancellablePromise<void> {
    return $Call.ByID(1376066862, root, file);
}

export function ShowFolder(root: string): $CancellablePromise<void> {
    return $Call.ByID(2287731004, root);
}

/**
 * ShowLogFolder opens the folder of the app's log (to attach to a report).
 */
export function ShowLogFolder(): $CancellablePromise<void> {
    return $Call.ByID(553296146);
}

/**
 * Signature changes when a set in the project is saved (or the project moves
 * to another version). It only looks at file sizes and times, and takes no
 * lock, so the frontend polls it to notice Ctrl+S in Live right away.
 */
export function Signature(root: string): $CancellablePromise<string> {
    return $Call.ByID(148784089, root);
}

/**
 * StartDrag drags files of the project (relative paths, all in one folder)
 * out of the app, while the mouse button is held; it returns when they are
 * dropped (true) or the drag is called off (false).
 */
export function StartDrag(root: string, files: string[]): $CancellablePromise<boolean> {
    return $Call.ByID(2640793345, root, files);
}

/**
 * StartTeamMove starts moving team teamID's projects (ids) to hosted team
 * toID with a read-only key (region "" for R2's "auto"); the plans and the
 * copy go on in the background.
 */
export function StartTeamMove(teamID: string, toID: string, projects: string[], accessKey: string, secretKey: string, region: string): $CancellablePromise<void> {
    return $Call.ByID(4101495143, teamID, toID, projects, accessKey, secretKey, region);
}

export function State(root: string): $CancellablePromise<$models.State | null> {
    return $Call.ByID(239642754, root).then(($result: any) => {
        return $$createType75($result);
    });
}

/**
 * StopBackup: this computer no longer backs up team teamID. The backup
 * folder is left as it is.
 */
export function StopBackup(teamID: string): $CancellablePromise<void> {
    return $Call.ByID(565094419, teamID);
}

export function SwitchBranch(root: string, name: string, force: boolean): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(3617511901, root, name, force).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * TakeBackVersion takes back the latest version id: gone from the history
 * (and the team's, when it was shared), its changes stay in the files,
 * uncommitted. turnOn turns taking back on for the team when it isn't.
 * Action "taken-back", or "taken-back-locally" when it wasn't shared.
 */
export function TakeBackVersion(root: string, id: string, turnOn: boolean): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(3021607643, root, id, turnOn).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * TeamConnectionCode is the code teammates paste to join a storage team.
 */
export function TeamConnectionCode(teamID: string): $CancellablePromise<string> {
    return $Call.ByID(946562893, teamID);
}

/**
 * TeamConnectionSettings returns how this computer reaches a team, keys
 * included (they are this user's own, shown in their settings).
 */
export function TeamConnectionSettings(teamID: string): $CancellablePromise<$models.TeamConnection> {
    return $Call.ByID(1833009493, teamID).then(($result: any) => {
        return $$createType76($result);
    });
}

/**
 * TeamLocks reads a team's lock settings.
 */
export function TeamLocks(teamID: string): $CancellablePromise<$models.TeamLocks | null> {
    return $Call.ByID(3829864204, teamID).then(($result: any) => {
        return $$createType78($result);
    });
}

/**
 * TeamMembers lists a team's members (to pick yourself on a new computer).
 */
export function TeamMembers(teamID: string): $CancellablePromise<remote$0.Member[]> {
    return $Call.ByID(2837059491, teamID).then(($result: any) => {
        return $$createType79($result);
    });
}

/**
 * TeamMoveState says how team teamID's move goes.
 */
export function TeamMoveState(teamID: string): $CancellablePromise<$models.TeamMoveState | null> {
    return $Call.ByID(1645171422, teamID).then(($result: any) => {
        return $$createType81($result);
    });
}

/**
 * TeamProjectsHere lists Local projects that are the team's (e.g. kept when
 * this computer disconnected from it), to offer reconnecting them.
 */
export function TeamProjectsHere(teamID: string): $CancellablePromise<$models.FoundProject[]> {
    return $Call.ByID(287030900, teamID).then(($result: any) => {
        return $$createType83($result);
    });
}

/**
 * TeamState asks the team for its branches and new versions. It runs
 * without the project lock, so the page shows State at once and fills this in.
 */
export function TeamState(root: string): $CancellablePromise<$models.TeamPart | null> {
    return $Call.ByID(132829061, root).then(($result: any) => {
        return $$createType85($result);
    });
}

/**
 * TextDiff compares a text file in two versions. A version is a version id,
 * "" for the project folder now, or "none" when there is no file to compare
 * with (it was added or deleted). whole: every line, not just the changes
 * with a few around them.
 * fromFile: the file's path in from, when it was elsewhere ("" for file).
 */
export function TextDiff(root: string, file: string, $from: string, to: string, whole: boolean, fromFile: string): $CancellablePromise<$models.TextChanges | null> {
    return $Call.ByID(3735057561, root, file, $from, to, whole, fromFile).then(($result: any) => {
        return $$createType87($result);
    });
}

/**
 * TextFile reads a text file in a version ("" for the project folder now).
 */
export function TextFile(root: string, file: string, version: string): $CancellablePromise<$models.TextContent | null> {
    return $Call.ByID(4211809220, root, file, version).then(($result: any) => {
        return $$createType89($result);
    });
}

/**
 * UnarchiveBranch puts archived branch key back where it was.
 */
export function UnarchiveBranch(root: string, key: string): $CancellablePromise<void> {
    return $Call.ByID(1047537852, root, key);
}

/**
 * UndoCommit makes a version that takes back version id's changes (keeping
 * what came after it) and shares it. Uncommitted changes in other files
 * stay. It rewrites files: not while Live has a set of the project open
 * (unless force).
 */
export function UndoCommit(root: string, id: string, message: string, resolutions: { [_ in string]?: string }, force: boolean): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(385380834, root, id, message, resolutions, force).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * UnlockFiles frees your locks on paths.
 */
export function UnlockFiles(root: string, paths: string[]): $CancellablePromise<void> {
    return $Call.ByID(1299024972, root, paths);
}

/**
 * UnwatchFiles ends a WatchFiles.
 */
export function UnwatchFiles(root: string): $CancellablePromise<void> {
    return $Call.ByID(2826667728, root);
}

/**
 * Update brings in the team's latest versions.
 */
export function Update(root: string, resolutions: { [_ in string]?: string }, force: boolean): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(3845137648, root, resolutions, force).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * UpdateStatus says how getting the update is going.
 */
export function UpdateStatus(): $CancellablePromise<$models.UpdateState> {
    return $Call.ByID(703339346).then(($result: any) => {
        return $$createType90($result);
    });
}

/**
 * UpdateTeamConnection changes how this computer reaches a team (new keys, a
 * moved bucket). The new settings are checked first. When the address
 * changes, the team's downloaded projects are pointed at it.
 */
export function UpdateTeamConnection(teamID: string, c: $models.TeamConnection): $CancellablePromise<$models.TeamSummary> {
    return $Call.ByID(1044340581, teamID, c).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * VerifyProject checks the project's history (every version, folder list
 * and stored file); with repair it brings back what it can.
 */
export function VerifyProject(root: string, repair: boolean): $CancellablePromise<$models.VerifyResult | null> {
    return $Call.ByID(1062480813, root, repair).then(($result: any) => {
        return $$createType92($result);
    });
}

/**
 * Version is the R3V release number.
 */
export function Version(): $CancellablePromise<string> {
    return $Call.ByID(4157249403);
}

/**
 * VersionChanges lists what a version changed compared with the one before
 * it (for a merge: what it brought into its branch), for the History tab.
 */
export function VersionChanges(root: string, id: string): $CancellablePromise<$models.Change[]> {
    return $Call.ByID(2982637732, root, id).then(($result: any) => {
        return $$createType94($result);
    });
}

/**
 * VersionFiles lists the files a version changed as the file viewers take
 * them (kind, previewable), for comparing each with the version before.
 */
export function VersionFiles(root: string, id: string): $CancellablePromise<$models.ProjectFile[]> {
    return $Call.ByID(2020744434, root, id).then(($result: any) => {
        return $$createType57($result);
    });
}

/**
 * VersionsOnlyOnBranch counts the versions of branch key no other branch
 * has (what archiving it leaves on no branch: they stay recoverable).
 */
export function VersionsOnlyOnBranch(root: string, key: string): $CancellablePromise<number> {
    return $Call.ByID(2795616315, root, key);
}

/**
 * WatchFiles sends "files" events when files in the project change, so new
 * or edited samples show up without waiting for the next poll. Sets are left
 * to Signature (it waits for Live to finish writing). It returns false when
 * this system has no watcher; each call wants an UnwatchFiles.
 */
export function WatchFiles(root: string): $CancellablePromise<boolean> {
    return $Call.ByID(3152483403, root);
}

/**
 * Workspaces lists the other copies of a project (who is working where,
 * with what), as they last told the team.
 */
export function Workspaces(root: string): $CancellablePromise<$models.Workspace[]> {
    return $Call.ByID(3970422323, root).then(($result: any) => {
        return $$createType96($result);
    });
}

// Private type creation functions
const $$createType0 = $models.TeamProject.createFrom;
const $$createType1 = $models.TeamProjects.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.ArchivedBranch.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.BackupInfo.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $models.BackupOthers.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = remote$0.Storage.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = $models.BranchList.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = $models.Result.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = $models.ChannelInfo.createFrom;
const $$createType16 = $models.UpdateInfo.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = $models.StorageCleanup.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = $models.TeamSummary.createFrom;
const $$createType21 = $models.CloudInvitation.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
const $$createType23 = $models.CloudPeople.createFrom;
const $$createType24 = $models.CloudStatus.createFrom;
const $$createType25 = $Create.Array($Create.Any);
const $$createType26 = $models.ConvertFormat.createFrom;
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = convert$0.Info.createFrom;
const $$createType29 = convert$0.Result.createFrom;
const $$createType30 = $models.DropResult.createFrom;
const $$createType31 = $Create.Nullable($$createType30);
const $$createType32 = teammove$0.Estimate.createFrom;
const $$createType33 = $Create.Nullable($$createType32);
const $$createType34 = $models.FileVersion.createFrom;
const $$createType35 = $Create.Array($$createType34);
const $$createType36 = $models.IgnoreOption.createFrom;
const $$createType37 = $Create.Array($$createType36);
const $$createType38 = $models.Version.createFrom;
const $$createType39 = $Create.Map($Create.Any, $$createType38);
const $$createType40 = $models.Overview.createFrom;
const $$createType41 = $Create.Nullable($$createType40);
const $$createType42 = $models.LockOutcome.createFrom;
const $$createType43 = $Create.Nullable($$createType42);
const $$createType44 = $models.MemberLook.createFrom;
const $$createType45 = $Create.Map($Create.Any, $$createType44);
const $$createType46 = $models.UndoPlan.createFrom;
const $$createType47 = $Create.Nullable($$createType46);
const $$createType48 = $models.Preupload.createFrom;
const $$createType49 = $Create.Array($$createType48);
const $$createType50 = $models.Preview.createFrom;
const $$createType51 = $Create.Nullable($$createType50);
const $$createType52 = $models.Profile.createFrom;
const $$createType53 = health$0.Report.createFrom;
const $$createType54 = $Create.Nullable($$createType53);
const $$createType55 = $models.DownloadSize.createFrom;
const $$createType56 = $models.ProjectFile.createFrom;
const $$createType57 = $Create.Array($$createType56);
const $$createType58 = $models.ProjectInfo.createFrom;
const $$createType59 = $Create.Nullable($$createType58);
const $$createType60 = $models.LocksView.createFrom;
const $$createType61 = $Create.Nullable($$createType60);
const $$createType62 = $models.RulesDetail.createFrom;
const $$createType63 = $Create.Nullable($$createType62);
const $$createType64 = $models.RestorePlan.createFrom;
const $$createType65 = $Create.Nullable($$createType64);
const $$createType66 = $models.RulesState.createFrom;
const $$createType67 = $Create.Nullable($$createType66);
const $$createType68 = $models.RuleNode.createFrom;
const $$createType69 = $Create.Array($$createType68);
const $$createType70 = $models.SampleSpot.createFrom;
const $$createType71 = $Create.Array($$createType70);
const $$createType72 = $models.SetView.createFrom;
const $$createType73 = $Create.Nullable($$createType72);
const $$createType74 = $models.State.createFrom;
const $$createType75 = $Create.Nullable($$createType74);
const $$createType76 = $models.TeamConnection.createFrom;
const $$createType77 = $models.TeamLocks.createFrom;
const $$createType78 = $Create.Nullable($$createType77);
const $$createType79 = $Create.Array($Create.Any);
const $$createType80 = teammove$0.State.createFrom;
const $$createType81 = $Create.Nullable($$createType80);
const $$createType82 = $models.FoundProject.createFrom;
const $$createType83 = $Create.Array($$createType82);
const $$createType84 = $models.TeamPart.createFrom;
const $$createType85 = $Create.Nullable($$createType84);
const $$createType86 = $models.TextChanges.createFrom;
const $$createType87 = $Create.Nullable($$createType86);
const $$createType88 = $models.TextContent.createFrom;
const $$createType89 = $Create.Nullable($$createType88);
const $$createType90 = $models.UpdateState.createFrom;
const $$createType91 = $models.VerifyResult.createFrom;
const $$createType92 = $Create.Nullable($$createType91);
const $$createType93 = $models.Change.createFrom;
const $$createType94 = $Create.Array($$createType93);
const $$createType95 = $models.Workspace.createFrom;
const $$createType96 = $Create.Array($$createType95);
