// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as als$0 from "../internal/als/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as backup$0 from "../internal/backup/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as profile$0 from "../internal/profile/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as project$0 from "../internal/project/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as remote$0 from "../internal/remote/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as textdiff$0 from "../internal/textdiff/models.js";

/**
 * BackupInfo is a team's backup, for Team Settings.
 */
export class BackupInfo {
    /**
     * Supported: the team keeps its work in storage (R2/S3).
     */
    "supported": boolean;

    /**
     * Kind: "folder" or "s3"; Folder: where (the folder, or the storage's
     * address, bucket and folder; no keys); "" when this computer doesn't
     * back up.
     */
    "kind": string;
    "folder": string;
    "paused": boolean;
    "running": boolean;
    "done": number;
    "total": number;

    /**
     * LastSuccess and LastAttempt: RFC 3339, "" for never.
     */
    "lastSuccess": string;
    "lastAttempt": string;

    /**
     * Problem: why the last run failed: "missing" (the folder isn't there:
     * a drive unplugged?), "other" (Error says), "" (it didn't).
     */
    "problem": string;
    "error": string;

    /**
     * failing for a while: worth a warning
     */
    "failing": boolean;
    "size": number;

    /** Creates a new BackupInfo instance. */
    constructor($$source: Partial<BackupInfo> = {}) {
        if (!("supported" in $$source)) {
            this["supported"] = false;
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("folder" in $$source)) {
            this["folder"] = "";
        }
        if (!("paused" in $$source)) {
            this["paused"] = false;
        }
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("done" in $$source)) {
            this["done"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("lastSuccess" in $$source)) {
            this["lastSuccess"] = "";
        }
        if (!("lastAttempt" in $$source)) {
            this["lastAttempt"] = "";
        }
        if (!("problem" in $$source)) {
            this["problem"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("failing" in $$source)) {
            this["failing"] = false;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackupInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): BackupInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BackupInfo($$parsedSource as Partial<BackupInfo>);
    }
}

/**
 * BackupOthers is how the team's other members back it up (asks the team:
 * BackupInfo shows this computer's at once, then this).
 */
export class BackupOthers {
    "others": MemberBackup[];

    /**
     * Covered: one of them backed it up lately.
     */
    "covered": boolean;

    /** Creates a new BackupOthers instance. */
    constructor($$source: Partial<BackupOthers> = {}) {
        if (!("others" in $$source)) {
            this["others"] = [];
        }
        if (!("covered" in $$source)) {
            this["covered"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackupOthers instance from a string or object.
     */
    static createFrom($$source: any = {}): BackupOthers {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("others" in $$parsedSource) {
            $$parsedSource["others"] = $$createField0_0($$parsedSource["others"]);
        }
        return new BackupOthers($$parsedSource as Partial<BackupOthers>);
    }
}

export class Branch {
    "name": string;
    "current": boolean;
    "latest": Version | null;

    /** Creates a new Branch instance. */
    constructor($$source: Partial<Branch> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("current" in $$source)) {
            this["current"] = false;
        }
        if (!("latest" in $$source)) {
            this["latest"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Branch instance from a string or object.
     */
    static createFrom($$source: any = {}): Branch {
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("latest" in $$parsedSource) {
            $$parsedSource["latest"] = $$createField2_0($$parsedSource["latest"]);
        }
        return new Branch($$parsedSource as Partial<Branch>);
    }
}

export class Change {
    "path": string;

    /**
     * added | modified | deleted | renamed | untracked
     */
    "status": string;

    /**
     * renamed: where it was
     */
    "from": string;

    /**
     * renamed: its content changed too
     */
    "edited": boolean;

    /**
     * semantic diff lines for sets
     */
    "details": string[];

    /**
     * Weight: for sets, the heaviest change (diff.Weight*: noise, tidy,
     * mix, sound, arrangement); "" for other files.
     */
    "weight": string;

    /**
     * for sets: each changed track and its weight
     */
    "tracks": TrackWeight[];

    /** Creates a new Change instance. */
    constructor($$source: Partial<Change> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("from" in $$source)) {
            this["from"] = "";
        }
        if (!("edited" in $$source)) {
            this["edited"] = false;
        }
        if (!("details" in $$source)) {
            this["details"] = [];
        }
        if (!("weight" in $$source)) {
            this["weight"] = "";
        }
        if (!("tracks" in $$source)) {
            this["tracks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Change instance from a string or object.
     */
    static createFrom($$source: any = {}): Change {
        const $$createField4_0 = $$createType4;
        const $$createField6_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("details" in $$parsedSource) {
            $$parsedSource["details"] = $$createField4_0($$parsedSource["details"]);
        }
        if ("tracks" in $$parsedSource) {
            $$parsedSource["tracks"] = $$createField6_0($$parsedSource["tracks"]);
        }
        return new Change($$parsedSource as Partial<Change>);
    }
}

/**
 * ChannelInfo is the update channel, for Settings.
 */
export class ChannelInfo {
    /**
     * this build's: "stable" or "nightly"
     */
    "build": string;

    /**
     * where updates come from
     */
    "chosen": string;

    /** Creates a new ChannelInfo instance. */
    constructor($$source: Partial<ChannelInfo> = {}) {
        if (!("build" in $$source)) {
            this["build"] = "";
        }
        if (!("chosen" in $$source)) {
            this["chosen"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChannelInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ChannelInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChannelInfo($$parsedSource as Partial<ChannelInfo>);
    }
}

export class Conflict {
    "key": string;
    "file": string;
    "unit": string;
    "description": string;
    "canKeepBoth": boolean;

    /** Creates a new Conflict instance. */
    constructor($$source: Partial<Conflict> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("file" in $$source)) {
            this["file"] = "";
        }
        if (!("unit" in $$source)) {
            this["unit"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("canKeepBoth" in $$source)) {
            this["canKeepBoth"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Conflict instance from a string or object.
     */
    static createFrom($$source: any = {}): Conflict {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Conflict($$parsedSource as Partial<Conflict>);
    }
}

/**
 * ConvertFormat is a format the Convert dialog offers.
 */
export class ConvertFormat {
    "id": string;
    "name": string;
    "ext": string;

    /**
     * kbps, first is the default; none for lossless
     */
    "bitrates": number[];

    /**
     * sample rates it takes (Hz)
     */
    "rates": number[];

    /**
     * bit depths to choose from (FLAC)
     */
    "bits": number[];

    /** Creates a new ConvertFormat instance. */
    constructor($$source: Partial<ConvertFormat> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("ext" in $$source)) {
            this["ext"] = "";
        }
        if (!("bitrates" in $$source)) {
            this["bitrates"] = [];
        }
        if (!("rates" in $$source)) {
            this["rates"] = [];
        }
        if (!("bits" in $$source)) {
            this["bits"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConvertFormat instance from a string or object.
     */
    static createFrom($$source: any = {}): ConvertFormat {
        const $$createField3_0 = $$createType7;
        const $$createField4_0 = $$createType7;
        const $$createField5_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bitrates" in $$parsedSource) {
            $$parsedSource["bitrates"] = $$createField3_0($$parsedSource["bitrates"]);
        }
        if ("rates" in $$parsedSource) {
            $$parsedSource["rates"] = $$createField4_0($$parsedSource["rates"]);
        }
        if ("bits" in $$parsedSource) {
            $$parsedSource["bits"] = $$createField5_0($$parsedSource["bits"]);
        }
        return new ConvertFormat($$parsedSource as Partial<ConvertFormat>);
    }
}

/**
 * DownloadSize is the size of a team project's latest version, shown
 * before downloading it.
 */
export class DownloadSize {
    "files": number;
    "bytes": number;

    /** Creates a new DownloadSize instance. */
    constructor($$source: Partial<DownloadSize> = {}) {
        if (!("files" in $$source)) {
            this["files"] = 0;
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadSize instance from a string or object.
     */
    static createFrom($$source: any = {}): DownloadSize {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadSize($$parsedSource as Partial<DownloadSize>);
    }
}

/**
 * FileVersion is a version that changed a file.
 */
export class FileVersion {
    "version": Version;

    /**
     * added | modified | deleted | renamed
     */
    "status": string;

    /**
     * where the file is in that version
     */
    "path": string;

    /**
     * renamed: where it was before
     */
    "from": string;

    /** Creates a new FileVersion instance. */
    constructor($$source: Partial<FileVersion> = {}) {
        if (!("version" in $$source)) {
            this["version"] = (new Version());
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("from" in $$source)) {
            this["from"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileVersion instance from a string or object.
     */
    static createFrom($$source: any = {}): FileVersion {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("version" in $$parsedSource) {
            $$parsedSource["version"] = $$createField0_0($$parsedSource["version"]);
        }
        return new FileVersion($$parsedSource as Partial<FileVersion>);
    }
}

/**
 * FoundProject is a project on this computer that belongs to a team.
 */
export class FoundProject {
    "root": string;
    "name": string;

    /** Creates a new FoundProject instance. */
    constructor($$source: Partial<FoundProject> = {}) {
        if (!("root" in $$source)) {
            this["root"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FoundProject instance from a string or object.
     */
    static createFrom($$source: any = {}): FoundProject {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FoundProject($$parsedSource as Partial<FoundProject>);
    }
}

/**
 * IgnoreOption is a rule offered for leaving a file or folder out.
 */
export class IgnoreOption {
    "label": string;
    "pattern": string;

    /** Creates a new IgnoreOption instance. */
    constructor($$source: Partial<IgnoreOption> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("pattern" in $$source)) {
            this["pattern"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IgnoreOption instance from a string or object.
     */
    static createFrom($$source: any = {}): IgnoreOption {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IgnoreOption($$parsedSource as Partial<IgnoreOption>);
    }
}

export class MemberBackup {
    "name": string;
    "lastSuccess": string;
    "failing": boolean;

    /** Creates a new MemberBackup instance. */
    constructor($$source: Partial<MemberBackup> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("lastSuccess" in $$source)) {
            this["lastSuccess"] = "";
        }
        if (!("failing" in $$source)) {
            this["failing"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MemberBackup instance from a string or object.
     */
    static createFrom($$source: any = {}): MemberBackup {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MemberBackup($$parsedSource as Partial<MemberBackup>);
    }
}

export class Overview {
    "author": string;
    "teams": TeamSummary[];
    "currentTeam": string;

    /**
     * of the current team
     */
    "projects": TeamProject[];
    "teamError": string;

    /**
     * TeamChecked: the team was asked (its projects not downloaded here are
     * listed, TeamError says if it couldn't be reached); LocalOverview
     * doesn't ask it.
     */
    "teamChecked": boolean;

    /** Creates a new Overview instance. */
    constructor($$source: Partial<Overview> = {}) {
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("teams" in $$source)) {
            this["teams"] = [];
        }
        if (!("currentTeam" in $$source)) {
            this["currentTeam"] = "";
        }
        if (!("projects" in $$source)) {
            this["projects"] = [];
        }
        if (!("teamError" in $$source)) {
            this["teamError"] = "";
        }
        if (!("teamChecked" in $$source)) {
            this["teamChecked"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Overview instance from a string or object.
     */
    static createFrom($$source: any = {}): Overview {
        const $$createField1_0 = $$createType9;
        const $$createField3_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("teams" in $$parsedSource) {
            $$parsedSource["teams"] = $$createField1_0($$parsedSource["teams"]);
        }
        if ("projects" in $$parsedSource) {
            $$parsedSource["projects"] = $$createField3_0($$parsedSource["projects"]);
        }
        return new Overview($$parsedSource as Partial<Overview>);
    }
}

/**
 * PresetOption is a preset the window offers.
 */
export class PresetOption {
    "name": string;

    /**
     * its ignore patterns
     */
    "leftOut": string[];

    /** Creates a new PresetOption instance. */
    constructor($$source: Partial<PresetOption> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("leftOut" in $$source)) {
            this["leftOut"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PresetOption instance from a string or object.
     */
    static createFrom($$source: any = {}): PresetOption {
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("leftOut" in $$parsedSource) {
            $$parsedSource["leftOut"] = $$createField1_0($$parsedSource["leftOut"]);
        }
        return new PresetOption($$parsedSource as Partial<PresetOption>);
    }
}

/**
 * Preupload is a file going up in the background (event "preupload": Done
 * false while it goes, true once it's up or stopped), and the project's big
 * files waiting to go after it.
 */
export class Preupload {
    "root": string;
    "path": string;
    "bytes": number;
    "total": number;
    "done": boolean;
    "waiting": PreuploadFile[];

    /** Creates a new Preupload instance. */
    constructor($$source: Partial<Preupload> = {}) {
        if (!("root" in $$source)) {
            this["root"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("done" in $$source)) {
            this["done"] = false;
        }
        if (!("waiting" in $$source)) {
            this["waiting"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Preupload instance from a string or object.
     */
    static createFrom($$source: any = {}): Preupload {
        const $$createField5_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("waiting" in $$parsedSource) {
            $$parsedSource["waiting"] = $$createField5_0($$parsedSource["waiting"]);
        }
        return new Preupload($$parsedSource as Partial<Preupload>);
    }
}

/**
 * PreuploadFile is a big file waiting to go up.
 */
export class PreuploadFile {
    "path": string;
    "size": number;

    /** Creates a new PreuploadFile instance. */
    constructor($$source: Partial<PreuploadFile> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreuploadFile instance from a string or object.
     */
    static createFrom($$source: any = {}): PreuploadFile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PreuploadFile($$parsedSource as Partial<PreuploadFile>);
    }
}

export class Preview {
    /**
     * up-to-date | ahead | fast-forward | merge
     */
    "action": string;
    "versions": Version[];
    "changes": Change[];
    "conflicts": Conflict[];

    /**
     * Message: for merges, the default description of the merge version.
     */
    "message": string;

    /**
     * Changes compare Base (where the two sides parted; "" none) with
     * Target (what comes in).
     */
    "base": string;
    "target": string;

    /** Creates a new Preview instance. */
    constructor($$source: Partial<Preview> = {}) {
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("versions" in $$source)) {
            this["versions"] = [];
        }
        if (!("changes" in $$source)) {
            this["changes"] = [];
        }
        if (!("conflicts" in $$source)) {
            this["conflicts"] = [];
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("base" in $$source)) {
            this["base"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Preview instance from a string or object.
     */
    static createFrom($$source: any = {}): Preview {
        const $$createField1_0 = $$createType14;
        const $$createField2_0 = $$createType16;
        const $$createField3_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("versions" in $$parsedSource) {
            $$parsedSource["versions"] = $$createField1_0($$parsedSource["versions"]);
        }
        if ("changes" in $$parsedSource) {
            $$parsedSource["changes"] = $$createField2_0($$parsedSource["changes"]);
        }
        if ("conflicts" in $$parsedSource) {
            $$parsedSource["conflicts"] = $$createField3_0($$parsedSource["conflicts"]);
        }
        return new Preview($$parsedSource as Partial<Preview>);
    }
}

/**
 * ProjectFile is a file as the Changes tab lists it.
 */
export class ProjectFile {
    "path": string;

    /**
     * added | modified | deleted | unchanged | ignored
     */
    "status": string;
    "size": number;

    /**
     * set | live (clip, preset, rack) | audio | midi | other
     */
    "kind": string;

    /**
     * Live is the Live that last saved a set, e.g. "Ableton Live 12.3.1".
     */
    "live": string;

    /**
     * Renamed: where it was, and whether its content changed too.
     */
    "from": string;
    "edited": boolean;

    /**
     * Preview: the app can show it as an image (/r3v-preview); Video:
     * it can try to play it; Model: a 3D model it can show.
     */
    "preview": boolean;
    "video": boolean;
    "model": boolean;

    /**
     * Modified: when the file in the project folder last changed (RFC 3339;
     * "" when it isn't there).
     */
    "modified": string;

    /** Creates a new ProjectFile instance. */
    constructor($$source: Partial<ProjectFile> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("live" in $$source)) {
            this["live"] = "";
        }
        if (!("from" in $$source)) {
            this["from"] = "";
        }
        if (!("edited" in $$source)) {
            this["edited"] = false;
        }
        if (!("preview" in $$source)) {
            this["preview"] = false;
        }
        if (!("video" in $$source)) {
            this["video"] = false;
        }
        if (!("model" in $$source)) {
            this["model"] = false;
        }
        if (!("modified" in $$source)) {
            this["modified"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectFile instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectFile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectFile($$parsedSource as Partial<ProjectFile>);
    }
}

/**
 * ProjectInfo is what a project's menu and settings show, read without
 * looking at its files (fast).
 */
export class ProjectInfo {
    "root": string;
    "name": string;
    "id": string;
    "branch": string;

    /**
     * the program it is made with ("" unknown)
     */
    "tool": string;

    /**
     * what "Open in <Tool>" offers
     */
    "openable": string[];
    "rules": RulesInfo;

    /** Creates a new ProjectInfo instance. */
    constructor($$source: Partial<ProjectInfo> = {}) {
        if (!("root" in $$source)) {
            this["root"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("tool" in $$source)) {
            this["tool"] = "";
        }
        if (!("openable" in $$source)) {
            this["openable"] = [];
        }
        if (!("rules" in $$source)) {
            this["rules"] = (new RulesInfo());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectInfo {
        const $$createField5_0 = $$createType4;
        const $$createField6_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("openable" in $$parsedSource) {
            $$parsedSource["openable"] = $$createField5_0($$parsedSource["openable"]);
        }
        if ("rules" in $$parsedSource) {
            $$parsedSource["rules"] = $$createField6_0($$parsedSource["rules"]);
        }
        return new ProjectInfo($$parsedSource as Partial<ProjectInfo>);
    }
}

/**
 * RestorePlan is what restoring a backup into the team's storage would
 * bring back (see backup.MakePlan).
 */
export class RestorePlan {
    /**
     * the backup: a folder, or a bucket's address
     */
    "where": string;

    /**
     * whose backup it is (the team's name then)
     */
    "team": string;

    /**
     * "" for the latest
     */
    "run": string;

    /**
     * newest first, as 20261004-153000 (UTC)
     */
    "runs": string[];
    "projects": backup$0.PlanProject[];
    "branches": number;
    "files": number;
    "bytes": number;

    /** Creates a new RestorePlan instance. */
    constructor($$source: Partial<RestorePlan> = {}) {
        if (!("where" in $$source)) {
            this["where"] = "";
        }
        if (!("team" in $$source)) {
            this["team"] = "";
        }
        if (!("run" in $$source)) {
            this["run"] = "";
        }
        if (!("runs" in $$source)) {
            this["runs"] = [];
        }
        if (!("projects" in $$source)) {
            this["projects"] = [];
        }
        if (!("branches" in $$source)) {
            this["branches"] = 0;
        }
        if (!("files" in $$source)) {
            this["files"] = 0;
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RestorePlan instance from a string or object.
     */
    static createFrom($$source: any = {}): RestorePlan {
        const $$createField3_0 = $$createType4;
        const $$createField4_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("runs" in $$parsedSource) {
            $$parsedSource["runs"] = $$createField3_0($$parsedSource["runs"]);
        }
        if ("projects" in $$parsedSource) {
            $$parsedSource["projects"] = $$createField4_0($$parsedSource["projects"]);
        }
        return new RestorePlan($$parsedSource as Partial<RestorePlan>);
    }
}

/**
 * RestoreSource is the backup to restore from: a folder, S3-compatible
 * storage (any bucket a backup went to, e.g. from another computer; its
 * keys are used for this restore only, and reading is enough), or, with
 * neither, where this computer backs the team up.
 */
export class RestoreSource {
    "folder": string;
    "storage": remote$0.Storage | null;

    /** Creates a new RestoreSource instance. */
    constructor($$source: Partial<RestoreSource> = {}) {
        if (!("folder" in $$source)) {
            this["folder"] = "";
        }
        if (!("storage" in $$source)) {
            this["storage"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RestoreSource instance from a string or object.
     */
    static createFrom($$source: any = {}): RestoreSource {
        const $$createField1_0 = $$createType23;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("storage" in $$parsedSource) {
            $$parsedSource["storage"] = $$createField1_0($$parsedSource["storage"]);
        }
        return new RestoreSource($$parsedSource as Partial<RestoreSource>);
    }
}

/**
 * Result of save / update / merge / switch.
 */
export class Result {
    "action": string;
    "log": string[];
    "relinked": string[];

    /**
     * Conflicts need decisions; nothing was changed. Call again with
     * resolutions keyed by Conflict.Key.
     */
    "conflicts": Conflict[];

    /**
     * LiveRunning: a set of this project is open in Ableton Live and must be
     * closed first (OpenSet names it; "" when it cannot be told); call again
     * with force when it is closed.
     */
    "liveRunning": boolean;
    "openSet": string;

    /**
     * KeptWork: uncommitted changes were kept through an update (still
     * uncommitted, the team's versions merged in).
     */
    "keptWork": boolean;

    /**
     * TakenBack: versions a teammate took back, taken out here too.
     */
    "takenBack": Version[];

    /** Creates a new Result instance. */
    constructor($$source: Partial<Result> = {}) {
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("log" in $$source)) {
            this["log"] = [];
        }
        if (!("relinked" in $$source)) {
            this["relinked"] = [];
        }
        if (!("conflicts" in $$source)) {
            this["conflicts"] = [];
        }
        if (!("liveRunning" in $$source)) {
            this["liveRunning"] = false;
        }
        if (!("openSet" in $$source)) {
            this["openSet"] = "";
        }
        if (!("keptWork" in $$source)) {
            this["keptWork"] = false;
        }
        if (!("takenBack" in $$source)) {
            this["takenBack"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     */
    static createFrom($$source: any = {}): Result {
        const $$createField1_0 = $$createType4;
        const $$createField2_0 = $$createType4;
        const $$createField3_0 = $$createType18;
        const $$createField7_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("log" in $$parsedSource) {
            $$parsedSource["log"] = $$createField1_0($$parsedSource["log"]);
        }
        if ("relinked" in $$parsedSource) {
            $$parsedSource["relinked"] = $$createField2_0($$parsedSource["relinked"]);
        }
        if ("conflicts" in $$parsedSource) {
            $$parsedSource["conflicts"] = $$createField3_0($$parsedSource["conflicts"]);
        }
        if ("takenBack" in $$parsedSource) {
            $$parsedSource["takenBack"] = $$createField7_0($$parsedSource["takenBack"]);
        }
        return new Result($$parsedSource as Partial<Result>);
    }
}

/**
 * RuleItem is a rule of .r3v.yaml.
 */
export class RuleItem {
    /**
     * ignore | track
     */
    "kind": string;
    "pattern": string;

    /** Creates a new RuleItem instance. */
    constructor($$source: Partial<RuleItem> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("pattern" in $$source)) {
            this["pattern"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuleItem instance from a string or object.
     */
    static createFrom($$source: any = {}): RuleItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RuleItem($$parsedSource as Partial<RuleItem>);
    }
}

/**
 * RuleNode is a file or folder in the Rules window's tree.
 */
export class RuleNode {
    "name": string;

    /**
     * relative to the project folder
     */
    "path": string;
    "dir": boolean;
    "ignored": boolean;

    /**
     * the rule or preset that decides
     */
    "by": string;

    /**
     * a folder presets: names: its preset
     */
    "preset": string;

    /**
     * files only
     */
    "size": number;

    /** Creates a new RuleNode instance. */
    constructor($$source: Partial<RuleNode> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("dir" in $$source)) {
            this["dir"] = false;
        }
        if (!("ignored" in $$source)) {
            this["ignored"] = false;
        }
        if (!("by" in $$source)) {
            this["by"] = "";
        }
        if (!("preset" in $$source)) {
            this["preset"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuleNode instance from a string or object.
     */
    static createFrom($$source: any = {}): RuleNode {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RuleNode($$parsedSource as Partial<RuleNode>);
    }
}

/**
 * RuleSuggestion is a project of a tool found in a folder the rules don't
 * name yet, with how much its preset would leave out there.
 */
export class RuleSuggestion {
    /**
     * "" the project folder
     */
    "folder": string;
    "preset": string;

    /**
     * LeftOut: what the preset leaves out there (its ignore patterns).
     */
    "leftOut": string[];

    /**
     * -1: not counted (too many files)
     */
    "leftOutBytes": number;

    /** Creates a new RuleSuggestion instance. */
    constructor($$source: Partial<RuleSuggestion> = {}) {
        if (!("folder" in $$source)) {
            this["folder"] = "";
        }
        if (!("preset" in $$source)) {
            this["preset"] = "";
        }
        if (!("leftOut" in $$source)) {
            this["leftOut"] = [];
        }
        if (!("leftOutBytes" in $$source)) {
            this["leftOutBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuleSuggestion instance from a string or object.
     */
    static createFrom($$source: any = {}): RuleSuggestion {
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("leftOut" in $$parsedSource) {
            $$parsedSource["leftOut"] = $$createField2_0($$parsedSource["leftOut"]);
        }
        return new RuleSuggestion($$parsedSource as Partial<RuleSuggestion>);
    }
}

/**
 * RulesDetail is what the window shows of a project's rules.
 */
export class RulesDetail {
    "presets": profile$0.PresetEntry[];
    "rules": RuleItem[];
    "suggestions": RuleSuggestion[];
    "options": PresetOption[];

    /**
     * the file can't be read: fix it as text
     */
    "error": string;

    /** Creates a new RulesDetail instance. */
    constructor($$source: Partial<RulesDetail> = {}) {
        if (!("presets" in $$source)) {
            this["presets"] = [];
        }
        if (!("rules" in $$source)) {
            this["rules"] = [];
        }
        if (!("suggestions" in $$source)) {
            this["suggestions"] = [];
        }
        if (!("options" in $$source)) {
            this["options"] = [];
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RulesDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): RulesDetail {
        const $$createField0_0 = $$createType25;
        const $$createField1_0 = $$createType27;
        const $$createField2_0 = $$createType29;
        const $$createField3_0 = $$createType31;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("presets" in $$parsedSource) {
            $$parsedSource["presets"] = $$createField0_0($$parsedSource["presets"]);
        }
        if ("rules" in $$parsedSource) {
            $$parsedSource["rules"] = $$createField1_0($$parsedSource["rules"]);
        }
        if ("suggestions" in $$parsedSource) {
            $$parsedSource["suggestions"] = $$createField2_0($$parsedSource["suggestions"]);
        }
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField3_0($$parsedSource["options"]);
        }
        return new RulesDetail($$parsedSource as Partial<RulesDetail>);
    }
}

/**
 * RulesInfo is how a project's rules come about (see profile).
 */
export class RulesInfo {
    /**
     * presets by folder
     */
    "applied": profile$0.Applied[];

    /**
     * a .r3v.yaml (else detected)
     */
    "fromFile": boolean;

    /**
     * why commits are refused
     */
    "error": string;

    /**
     * Suggestions: projects of tools found in folders the rules don't name
     * yet (asked about before committing).
     */
    "suggestions": RuleSuggestion[];

    /** Creates a new RulesInfo instance. */
    constructor($$source: Partial<RulesInfo> = {}) {
        if (!("applied" in $$source)) {
            this["applied"] = [];
        }
        if (!("fromFile" in $$source)) {
            this["fromFile"] = false;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("suggestions" in $$source)) {
            this["suggestions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RulesInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): RulesInfo {
        const $$createField0_0 = $$createType33;
        const $$createField3_0 = $$createType29;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("applied" in $$parsedSource) {
            $$parsedSource["applied"] = $$createField0_0($$parsedSource["applied"]);
        }
        if ("suggestions" in $$parsedSource) {
            $$parsedSource["suggestions"] = $$createField3_0($$parsedSource["suggestions"]);
        }
        return new RulesInfo($$parsedSource as Partial<RulesInfo>);
    }
}

/**
 * SampleSpot is a sample the project's sets use that is missing or only in
 * R3V's hidden .r3v folder (see project.SampleSpots).
 */
export class SampleSpot {
    "path": string;
    "name": string;
    "size": number;
    "missing": boolean;

    /**
     * in .r3v: gone with it
     */
    "kept": boolean;

    /**
     * missing, and R3V has a copy
     */
    "restorable": boolean;
    "sets": string[];

    /** Creates a new SampleSpot instance. */
    constructor($$source: Partial<SampleSpot> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("missing" in $$source)) {
            this["missing"] = false;
        }
        if (!("kept" in $$source)) {
            this["kept"] = false;
        }
        if (!("restorable" in $$source)) {
            this["restorable"] = false;
        }
        if (!("sets" in $$source)) {
            this["sets"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SampleSpot instance from a string or object.
     */
    static createFrom($$source: any = {}): SampleSpot {
        const $$createField6_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sets" in $$parsedSource) {
            $$parsedSource["sets"] = $$createField6_0($$parsedSource["sets"]);
        }
        return new SampleSpot($$parsedSource as Partial<SampleSpot>);
    }
}

export class SetTrackChange {
    "id": string;

    /**
     * added | removed | modified
     */
    "status": string;
    "details": string[];

    /**
     * the track's heaviest change
     */
    "weight": string;

    /**
     * each detail's
     */
    "weights": string[];

    /** Creates a new SetTrackChange instance. */
    constructor($$source: Partial<SetTrackChange> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("details" in $$source)) {
            this["details"] = [];
        }
        if (!("weight" in $$source)) {
            this["weight"] = "";
        }
        if (!("weights" in $$source)) {
            this["weights"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SetTrackChange instance from a string or object.
     */
    static createFrom($$source: any = {}): SetTrackChange {
        const $$createField2_0 = $$createType4;
        const $$createField4_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("details" in $$parsedSource) {
            $$parsedSource["details"] = $$createField2_0($$parsedSource["details"]);
        }
        if ("weights" in $$parsedSource) {
            $$parsedSource["weights"] = $$createField4_0($$parsedSource["weights"]);
        }
        return new SetTrackChange($$parsedSource as Partial<SetTrackChange>);
    }
}

/**
 * SetView is a Live Set drawn as Live shows it, and how its tracks changed
 * from another version of it.
 */
export class SetView {
    /**
     * nil: no set in that version
     */
    "now": als$0.Overview | null;

    /**
     * nil: nothing to compare with
     */
    "before": als$0.Overview | null;

    /**
     * tempo, main track, ...
     */
    "global": string[];

    /**
     * GlobalWeights weigh Global (diff.Weight*); Weight is the heaviest
     * change of all.
     */
    "globalWeights": string[];
    "weight": string;

    /**
     * the tracks' order changed
     */
    "order": boolean;
    "changes": SetTrackChange[];

    /**
     * the changes as text lines
     */
    "text": string[];

    /** Creates a new SetView instance. */
    constructor($$source: Partial<SetView> = {}) {
        if (!("now" in $$source)) {
            this["now"] = null;
        }
        if (!("before" in $$source)) {
            this["before"] = null;
        }
        if (!("global" in $$source)) {
            this["global"] = [];
        }
        if (!("globalWeights" in $$source)) {
            this["globalWeights"] = [];
        }
        if (!("weight" in $$source)) {
            this["weight"] = "";
        }
        if (!("order" in $$source)) {
            this["order"] = false;
        }
        if (!("changes" in $$source)) {
            this["changes"] = [];
        }
        if (!("text" in $$source)) {
            this["text"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SetView instance from a string or object.
     */
    static createFrom($$source: any = {}): SetView {
        const $$createField0_0 = $$createType35;
        const $$createField1_0 = $$createType35;
        const $$createField2_0 = $$createType4;
        const $$createField3_0 = $$createType4;
        const $$createField6_0 = $$createType37;
        const $$createField7_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("now" in $$parsedSource) {
            $$parsedSource["now"] = $$createField0_0($$parsedSource["now"]);
        }
        if ("before" in $$parsedSource) {
            $$parsedSource["before"] = $$createField1_0($$parsedSource["before"]);
        }
        if ("global" in $$parsedSource) {
            $$parsedSource["global"] = $$createField2_0($$parsedSource["global"]);
        }
        if ("globalWeights" in $$parsedSource) {
            $$parsedSource["globalWeights"] = $$createField3_0($$parsedSource["globalWeights"]);
        }
        if ("changes" in $$parsedSource) {
            $$parsedSource["changes"] = $$createField6_0($$parsedSource["changes"]);
        }
        if ("text" in $$parsedSource) {
            $$parsedSource["text"] = $$createField7_0($$parsedSource["text"]);
        }
        return new SetView($$parsedSource as Partial<SetView>);
    }
}

export class State {
    "rules": RulesInfo;
    "root": string;
    "name": string;
    "author": string;
    "branch": string;
    "remoteUrl": string;

    /**
     * "" for a project kept on this computer only
     */
    "teamId": string;
    "teamName": string;

    /**
     * TeamChecked: the team fields below come from a TeamState call (false
     * until one ran for this project since R3V started).
     */
    "teamChecked": boolean;

    /**
     * from TeamState: versions here, none on the team yet
     */
    "unshared": boolean;
    "online": boolean;

    /**
     * why the team's storage is unreachable
     */
    "offline": string;

    /**
     * a set of this project is open in Live
     */
    "liveRunning": boolean;
    "head": string;

    /**
     * Tool is the program the project is made with ("Ableton Live", "Unity";
     * "" when its rules don't say); Openable what "Open in <Tool>" offers
     * (relative paths, "." for the project folder).
     */
    "tool": string;
    "openable": string[];

    /**
     * OlderVersion is the version the project was moved back to (Go to
     * version); nil on the latest version. Latest is the branch's newest.
     */
    "olderVersion": Version | null;
    "latest": string;

    /**
     * Unfinished is the version a switch was putting in place when it
     * stopped halfway (R3V closed, a file in use); nil normally. The
     * project is still on Head (OlderVersion or the latest).
     */
    "unfinished": Version | null;

    /**
     * CloudFolder names the syncing service whose folder holds the project
     * (OneDrive, Dropbox…); "" when none.
     */
    "cloudFolder": string;
    "changes": Change[];

    /**
     * InUse: files another program holds (Live writing a Freeze), read once
     * they are free; until then they count as in the version you are on.
     */
    "inUse": string[];
    "myEdits": project$0.TrackEdit[];
    "incoming": Version[];

    /**
     * TakenBack: versions here a teammate took back (Update takes them out).
     */
    "takenBack": Version[];
    "history": Version[];
    "branches": Branch[];

    /** Creates a new State instance. */
    constructor($$source: Partial<State> = {}) {
        if (!("rules" in $$source)) {
            this["rules"] = (new RulesInfo());
        }
        if (!("root" in $$source)) {
            this["root"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("remoteUrl" in $$source)) {
            this["remoteUrl"] = "";
        }
        if (!("teamId" in $$source)) {
            this["teamId"] = "";
        }
        if (!("teamName" in $$source)) {
            this["teamName"] = "";
        }
        if (!("teamChecked" in $$source)) {
            this["teamChecked"] = false;
        }
        if (!("unshared" in $$source)) {
            this["unshared"] = false;
        }
        if (!("online" in $$source)) {
            this["online"] = false;
        }
        if (!("offline" in $$source)) {
            this["offline"] = "";
        }
        if (!("liveRunning" in $$source)) {
            this["liveRunning"] = false;
        }
        if (!("head" in $$source)) {
            this["head"] = "";
        }
        if (!("tool" in $$source)) {
            this["tool"] = "";
        }
        if (!("openable" in $$source)) {
            this["openable"] = [];
        }
        if (!("olderVersion" in $$source)) {
            this["olderVersion"] = null;
        }
        if (!("latest" in $$source)) {
            this["latest"] = "";
        }
        if (!("unfinished" in $$source)) {
            this["unfinished"] = null;
        }
        if (!("cloudFolder" in $$source)) {
            this["cloudFolder"] = "";
        }
        if (!("changes" in $$source)) {
            this["changes"] = [];
        }
        if (!("inUse" in $$source)) {
            this["inUse"] = [];
        }
        if (!("myEdits" in $$source)) {
            this["myEdits"] = [];
        }
        if (!("incoming" in $$source)) {
            this["incoming"] = [];
        }
        if (!("takenBack" in $$source)) {
            this["takenBack"] = [];
        }
        if (!("history" in $$source)) {
            this["history"] = [];
        }
        if (!("branches" in $$source)) {
            this["branches"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new State instance from a string or object.
     */
    static createFrom($$source: any = {}): State {
        const $$createField0_0 = $$createType19;
        const $$createField15_0 = $$createType4;
        const $$createField16_0 = $$createType3;
        const $$createField18_0 = $$createType3;
        const $$createField20_0 = $$createType16;
        const $$createField21_0 = $$createType4;
        const $$createField22_0 = $$createType39;
        const $$createField23_0 = $$createType14;
        const $$createField24_0 = $$createType14;
        const $$createField25_0 = $$createType14;
        const $$createField26_0 = $$createType41;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rules" in $$parsedSource) {
            $$parsedSource["rules"] = $$createField0_0($$parsedSource["rules"]);
        }
        if ("openable" in $$parsedSource) {
            $$parsedSource["openable"] = $$createField15_0($$parsedSource["openable"]);
        }
        if ("olderVersion" in $$parsedSource) {
            $$parsedSource["olderVersion"] = $$createField16_0($$parsedSource["olderVersion"]);
        }
        if ("unfinished" in $$parsedSource) {
            $$parsedSource["unfinished"] = $$createField18_0($$parsedSource["unfinished"]);
        }
        if ("changes" in $$parsedSource) {
            $$parsedSource["changes"] = $$createField20_0($$parsedSource["changes"]);
        }
        if ("inUse" in $$parsedSource) {
            $$parsedSource["inUse"] = $$createField21_0($$parsedSource["inUse"]);
        }
        if ("myEdits" in $$parsedSource) {
            $$parsedSource["myEdits"] = $$createField22_0($$parsedSource["myEdits"]);
        }
        if ("incoming" in $$parsedSource) {
            $$parsedSource["incoming"] = $$createField23_0($$parsedSource["incoming"]);
        }
        if ("takenBack" in $$parsedSource) {
            $$parsedSource["takenBack"] = $$createField24_0($$parsedSource["takenBack"]);
        }
        if ("history" in $$parsedSource) {
            $$parsedSource["history"] = $$createField25_0($$parsedSource["history"]);
        }
        if ("branches" in $$parsedSource) {
            $$parsedSource["branches"] = $$createField26_0($$parsedSource["branches"]);
        }
        return new State($$parsedSource as Partial<State>);
    }
}

/**
 * StorageCleanup is what cleaning up a team's storage found (and did).
 */
export class StorageCleanup {
    /**
     * version records read, all projects
     */
    "versions": number;

    /**
     * files in storage
     */
    "stored": number;

    /**
     * Unused files: due for deleting now; waiting (all unused, when only
     * checking); deleted.
     */
    "unused": number;
    "unusedBytes": number;
    "due": number;
    "dueBytes": number;
    "deleted": number;
    "deletedBytes": number;

    /**
     * when waiting files can go (RFC 3339), "" if none
     */
    "nextCleanup": string;

    /** Creates a new StorageCleanup instance. */
    constructor($$source: Partial<StorageCleanup> = {}) {
        if (!("versions" in $$source)) {
            this["versions"] = 0;
        }
        if (!("stored" in $$source)) {
            this["stored"] = 0;
        }
        if (!("unused" in $$source)) {
            this["unused"] = 0;
        }
        if (!("unusedBytes" in $$source)) {
            this["unusedBytes"] = 0;
        }
        if (!("due" in $$source)) {
            this["due"] = 0;
        }
        if (!("dueBytes" in $$source)) {
            this["dueBytes"] = 0;
        }
        if (!("deleted" in $$source)) {
            this["deleted"] = 0;
        }
        if (!("deletedBytes" in $$source)) {
            this["deletedBytes"] = 0;
        }
        if (!("nextCleanup" in $$source)) {
            this["nextCleanup"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StorageCleanup instance from a string or object.
     */
    static createFrom($$source: any = {}): StorageCleanup {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StorageCleanup($$parsedSource as Partial<StorageCleanup>);
    }
}

/**
 * TakeBack says whether the latest version can be taken back instead:
 * gone from the history, its changes uncommitted here (see
 * project.PlanTakeBack).
 */
export class TakeBack {
    "ok": boolean;

    /**
     * Why not: older-version | not-latest | not-yours | who | merge | first |
     * has-it | on-branch; "" when OK.
     */
    "why": string;

    /**
     * names of who has it
     */
    "haveIt": string[];

    /**
     * other branches that have it
     */
    "branches": string[];

    /**
     * Shared: the team has it (else it is only here). FeatureOff: taking it
     * back turns taking back on for the team.
     */
    "shared": boolean;
    "featureOff": boolean;

    /** Creates a new TakeBack instance. */
    constructor($$source: Partial<TakeBack> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }
        if (!("why" in $$source)) {
            this["why"] = "";
        }
        if (!("haveIt" in $$source)) {
            this["haveIt"] = [];
        }
        if (!("branches" in $$source)) {
            this["branches"] = [];
        }
        if (!("shared" in $$source)) {
            this["shared"] = false;
        }
        if (!("featureOff" in $$source)) {
            this["featureOff"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TakeBack instance from a string or object.
     */
    static createFrom($$source: any = {}): TakeBack {
        const $$createField2_0 = $$createType4;
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("haveIt" in $$parsedSource) {
            $$parsedSource["haveIt"] = $$createField2_0($$parsedSource["haveIt"]);
        }
        if ("branches" in $$parsedSource) {
            $$parsedSource["branches"] = $$createField3_0($$parsedSource["branches"]);
        }
        return new TakeBack($$parsedSource as Partial<TakeBack>);
    }
}

/**
 * TeamConnection is how this computer reaches a team: its storage fields.
 * A team on a backend an extension added has only its address, shown as is.
 */
export class TeamConnection {
    "storage": boolean;
    "settings": remote$0.Storage;
    "address": string;

    /** Creates a new TeamConnection instance. */
    constructor($$source: Partial<TeamConnection> = {}) {
        if (!("storage" in $$source)) {
            this["storage"] = false;
        }
        if (!("settings" in $$source)) {
            this["settings"] = (new remote$0.Storage());
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TeamConnection instance from a string or object.
     */
    static createFrom($$source: any = {}): TeamConnection {
        const $$createField1_0 = $$createType22;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField1_0($$parsedSource["settings"]);
        }
        return new TeamConnection($$parsedSource as Partial<TeamConnection>);
    }
}

/**
 * TeamPart is the team's side of a project's state (see TeamState).
 */
export class TeamPart {
    "online": boolean;
    "offline": string;
    "branches": Branch[];
    "incoming": Version[];

    /**
     * see State.TakenBack
     */
    "takenBack": Version[];

    /**
     * all branches, with the team's
     */
    "history": Version[];
    "olderVersion": Version | null;

    /**
     * Unshared: this branch has versions here and none on the team yet (the
     * project was added and not shared).
     */
    "unshared": boolean;

    /**
     * Capabilities of the team's backend (locks, presence…): the app shows
     * what goes with them only when it has them.
     */
    "capabilities": remote$0.Capabilities;

    /** Creates a new TeamPart instance. */
    constructor($$source: Partial<TeamPart> = {}) {
        if (!("online" in $$source)) {
            this["online"] = false;
        }
        if (!("offline" in $$source)) {
            this["offline"] = "";
        }
        if (!("branches" in $$source)) {
            this["branches"] = [];
        }
        if (!("incoming" in $$source)) {
            this["incoming"] = [];
        }
        if (!("takenBack" in $$source)) {
            this["takenBack"] = [];
        }
        if (!("history" in $$source)) {
            this["history"] = [];
        }
        if (!("olderVersion" in $$source)) {
            this["olderVersion"] = null;
        }
        if (!("unshared" in $$source)) {
            this["unshared"] = false;
        }
        if (!("capabilities" in $$source)) {
            this["capabilities"] = (new remote$0.Capabilities());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TeamPart instance from a string or object.
     */
    static createFrom($$source: any = {}): TeamPart {
        const $$createField2_0 = $$createType41;
        const $$createField3_0 = $$createType14;
        const $$createField4_0 = $$createType14;
        const $$createField5_0 = $$createType14;
        const $$createField6_0 = $$createType3;
        const $$createField8_0 = $$createType42;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("branches" in $$parsedSource) {
            $$parsedSource["branches"] = $$createField2_0($$parsedSource["branches"]);
        }
        if ("incoming" in $$parsedSource) {
            $$parsedSource["incoming"] = $$createField3_0($$parsedSource["incoming"]);
        }
        if ("takenBack" in $$parsedSource) {
            $$parsedSource["takenBack"] = $$createField4_0($$parsedSource["takenBack"]);
        }
        if ("history" in $$parsedSource) {
            $$parsedSource["history"] = $$createField5_0($$parsedSource["history"]);
        }
        if ("olderVersion" in $$parsedSource) {
            $$parsedSource["olderVersion"] = $$createField6_0($$parsedSource["olderVersion"]);
        }
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField8_0($$parsedSource["capabilities"]);
        }
        return new TeamPart($$parsedSource as Partial<TeamPart>);
    }
}

/**
 * TeamProject is a project as the sidebar shows it.
 */
export class TeamProject {
    "id": string;
    "name": string;
    "root": string;

    /**
     * Status: "downloaded" (folder here), "remote" (on the team only),
     * "missing" (downloaded before, folder not found), "local" (no team).
     */
    "status": string;
    "branch": string;

    /** Creates a new TeamProject instance. */
    constructor($$source: Partial<TeamProject> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("root" in $$source)) {
            this["root"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TeamProject instance from a string or object.
     */
    static createFrom($$source: any = {}): TeamProject {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TeamProject($$parsedSource as Partial<TeamProject>);
    }
}

export class TeamSummary {
    "id": string;
    "name": string;
    "address": string;
    "isStorage": boolean;

    /**
     * Who this computer is in the team ("" until chosen).
     */
    "memberId": string;
    "memberName": string;

    /**
     * KeysUnreadable: this computer can't read the team's keys (settings
     * copied from another computer or Windows user).
     */
    "keysUnreadable": boolean;

    /**
     * ShareSetup: this computer shares its setup with the team;
     * CanShareSetup: the team's storage keeps setups (a backend an extension
     * added may not).
     */
    "shareSetup": boolean;
    "canShareSetup": boolean;

    /**
     * Preupload: big files go up in the background before they're
     * committed (on this computer; storage teams).
     */
    "preupload": boolean;

    /**
     * AskShareSetup: the app should ask whether to share it (not chosen yet).
     */
    "askShareSetup": boolean;

    /**
     * BackupFailing: this computer's backups of the team have failed for a
     * while (see BackupInfo).
     */
    "backupFailing": boolean;

    /** Creates a new TeamSummary instance. */
    constructor($$source: Partial<TeamSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("isStorage" in $$source)) {
            this["isStorage"] = false;
        }
        if (!("memberId" in $$source)) {
            this["memberId"] = "";
        }
        if (!("memberName" in $$source)) {
            this["memberName"] = "";
        }
        if (!("keysUnreadable" in $$source)) {
            this["keysUnreadable"] = false;
        }
        if (!("shareSetup" in $$source)) {
            this["shareSetup"] = false;
        }
        if (!("canShareSetup" in $$source)) {
            this["canShareSetup"] = false;
        }
        if (!("preupload" in $$source)) {
            this["preupload"] = false;
        }
        if (!("askShareSetup" in $$source)) {
            this["askShareSetup"] = false;
        }
        if (!("backupFailing" in $$source)) {
            this["backupFailing"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TeamSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): TeamSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TeamSummary($$parsedSource as Partial<TeamSummary>);
    }
}

/**
 * TextChanges is how a text file changed, line by line.
 */
export class TextChanges {
    /**
     * false: not text, or too big to compare
     */
    "text": boolean;

    /**
     * over maxTextDiff
     */
    "tooBig": boolean;

    /**
     * lines
     */
    "added": number;

    /**
     * lines
     */
    "removed": number;

    /**
     * the changes with lines around them
     */
    "hunks": textdiff$0.Hunk[];

    /**
     * more changes than shown
     */
    "truncated": boolean;

    /** Creates a new TextChanges instance. */
    constructor($$source: Partial<TextChanges> = {}) {
        if (!("text" in $$source)) {
            this["text"] = false;
        }
        if (!("tooBig" in $$source)) {
            this["tooBig"] = false;
        }
        if (!("added" in $$source)) {
            this["added"] = 0;
        }
        if (!("removed" in $$source)) {
            this["removed"] = 0;
        }
        if (!("hunks" in $$source)) {
            this["hunks"] = [];
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TextChanges instance from a string or object.
     */
    static createFrom($$source: any = {}): TextChanges {
        const $$createField4_0 = $$createType44;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("hunks" in $$parsedSource) {
            $$parsedSource["hunks"] = $$createField4_0($$parsedSource["hunks"]);
        }
        return new TextChanges($$parsedSource as Partial<TextChanges>);
    }
}

/**
 * TextContent is a text file's lines (TextFile).
 */
export class TextContent {
    /**
     * false: not text, too big, or no file
     */
    "text": boolean;

    /**
     * over maxTextDiff
     */
    "tooBig": boolean;
    "lines": string[];

    /**
     * more lines than sent
     */
    "truncated": boolean;

    /** Creates a new TextContent instance. */
    constructor($$source: Partial<TextContent> = {}) {
        if (!("text" in $$source)) {
            this["text"] = false;
        }
        if (!("tooBig" in $$source)) {
            this["tooBig"] = false;
        }
        if (!("lines" in $$source)) {
            this["lines"] = [];
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TextContent instance from a string or object.
     */
    static createFrom($$source: any = {}): TextContent {
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lines" in $$parsedSource) {
            $$parsedSource["lines"] = $$createField2_0($$parsedSource["lines"]);
        }
        return new TextContent($$parsedSource as Partial<TextContent>);
    }
}

/**
 * TrackWeight is a changed track of a set and how much it changed.
 */
export class TrackWeight {
    "name": string;

    /**
     * added | removed | modified
     */
    "status": string;
    "weight": string;

    /** Creates a new TrackWeight instance. */
    constructor($$source: Partial<TrackWeight> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("weight" in $$source)) {
            this["weight"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrackWeight instance from a string or object.
     */
    static createFrom($$source: any = {}): TrackWeight {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TrackWeight($$parsedSource as Partial<TrackWeight>);
    }
}

/**
 * UndoPlan is what undoing a version would do (for its confirmation): the
 * files it changes, the uncommitted changes in the way, and conflicts with
 * later versions to decide.
 */
export class UndoPlan {
    "changed": string[];
    "blocked": string[];
    "conflicts": Conflict[];

    /**
     * Error: why it can't be undone with a new version ("" when it can).
     */
    "error": string;
    "takeBack": TakeBack;

    /** Creates a new UndoPlan instance. */
    constructor($$source: Partial<UndoPlan> = {}) {
        if (!("changed" in $$source)) {
            this["changed"] = [];
        }
        if (!("blocked" in $$source)) {
            this["blocked"] = [];
        }
        if (!("conflicts" in $$source)) {
            this["conflicts"] = [];
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("takeBack" in $$source)) {
            this["takeBack"] = (new TakeBack());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UndoPlan instance from a string or object.
     */
    static createFrom($$source: any = {}): UndoPlan {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType4;
        const $$createField2_0 = $$createType18;
        const $$createField4_0 = $$createType45;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("changed" in $$parsedSource) {
            $$parsedSource["changed"] = $$createField0_0($$parsedSource["changed"]);
        }
        if ("blocked" in $$parsedSource) {
            $$parsedSource["blocked"] = $$createField1_0($$parsedSource["blocked"]);
        }
        if ("conflicts" in $$parsedSource) {
            $$parsedSource["conflicts"] = $$createField2_0($$parsedSource["conflicts"]);
        }
        if ("takeBack" in $$parsedSource) {
            $$parsedSource["takeBack"] = $$createField4_0($$parsedSource["takeBack"]);
        }
        return new UndoPlan($$parsedSource as Partial<UndoPlan>);
    }
}

/**
 * UpdateInfo describes a newer release than the one running.
 */
export class UpdateInfo {
    "version": string;

    /**
     * what's new
     */
    "pageUrl": string;

    /**
     * the installer ("" if none)
     */
    "downloadUrl": string;

    /**
     * Installable: signed, so R3V downloads and installs it itself (else
     * the installer is only offered as a download).
     */
    "installable": boolean;

    /**
     * Required: this version is too old to keep working (the release says
     * so, e.g. a new version format): it must be updated.
     */
    "required": boolean;

    /** Creates a new UpdateInfo instance. */
    constructor($$source: Partial<UpdateInfo> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("pageUrl" in $$source)) {
            this["pageUrl"] = "";
        }
        if (!("downloadUrl" in $$source)) {
            this["downloadUrl"] = "";
        }
        if (!("installable" in $$source)) {
            this["installable"] = false;
        }
        if (!("required" in $$source)) {
            this["required"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo($$parsedSource as Partial<UpdateInfo>);
    }
}

/**
 * UpdateState is how getting an update is going.
 */
export class UpdateState {
    /**
     * "" | "downloading" | "ready" | "failed"
     */
    "stage": string;

    /**
     * bytes
     */
    "done": number;
    "total": number;
    "error": string;

    /**
     * installed on its own (see SetAutoUpdate)
     */
    "auto": boolean;

    /** Creates a new UpdateState instance. */
    constructor($$source: Partial<UpdateState> = {}) {
        if (!("stage" in $$source)) {
            this["stage"] = "";
        }
        if (!("done" in $$source)) {
            this["done"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("auto" in $$source)) {
            this["auto"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateState instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateState($$parsedSource as Partial<UpdateState>);
    }
}

export class VerifyProblem {
    /**
     * version | folder-list | file
     */
    "kind": string;

    /**
     * a path, or a short id
     */
    "what": string;
    "detail": string;
    "fixed": boolean;

    /**
     * how it was repaired, or why it can't be
     */
    "how": string;

    /** Creates a new VerifyProblem instance. */
    constructor($$source: Partial<VerifyProblem> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("what" in $$source)) {
            this["what"] = "";
        }
        if (!("detail" in $$source)) {
            this["detail"] = "";
        }
        if (!("fixed" in $$source)) {
            this["fixed"] = false;
        }
        if (!("how" in $$source)) {
            this["how"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VerifyProblem instance from a string or object.
     */
    static createFrom($$source: any = {}): VerifyProblem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VerifyProblem($$parsedSource as Partial<VerifyProblem>);
    }
}

/**
 * VerifyResult is what checking a project's history found (VerifyProject).
 */
export class VerifyResult {
    "summary": string;

    /**
     * TeamChecked: the team's storage was asked about the files only it has;
     * InTeam: the project has a team (so it could have been).
     */
    "teamChecked": boolean;
    "inTeam": boolean;
    "problems": VerifyProblem[];

    /** Creates a new VerifyResult instance. */
    constructor($$source: Partial<VerifyResult> = {}) {
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("teamChecked" in $$source)) {
            this["teamChecked"] = false;
        }
        if (!("inTeam" in $$source)) {
            this["inTeam"] = false;
        }
        if (!("problems" in $$source)) {
            this["problems"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VerifyResult instance from a string or object.
     */
    static createFrom($$source: any = {}): VerifyResult {
        const $$createField3_0 = $$createType47;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("problems" in $$parsedSource) {
            $$parsedSource["problems"] = $$createField3_0($$parsedSource["problems"]);
        }
        return new VerifyResult($$parsedSource as Partial<VerifyResult>);
    }
}

export class Version {
    "id": string;
    "short": string;
    "author": string;

    /**
     * RFC 3339
     */
    "time": string;
    "message": string;
    "parents": string[];

    /**
     * team branches whose latest version this is
     */
    "branches": string[];

    /**
     * team member id ("" for older versions)
     */
    "authorId": string;

    /**
     * InBranch: the current branch already contains this version (only set
     * in State.History); other versions can be merged in.
     */
    "inBranch": boolean;

    /**
     * NotHere: some of its files are only in the storage of a team the
     * project is no longer in (going to it needs that team).
     */
    "notHere": boolean;

    /** Creates a new Version instance. */
    constructor($$source: Partial<Version> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("short" in $$source)) {
            this["short"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("time" in $$source)) {
            this["time"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("parents" in $$source)) {
            this["parents"] = [];
        }
        if (!("branches" in $$source)) {
            this["branches"] = [];
        }
        if (!("authorId" in $$source)) {
            this["authorId"] = "";
        }
        if (!("inBranch" in $$source)) {
            this["inBranch"] = false;
        }
        if (!("notHere" in $$source)) {
            this["notHere"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Version instance from a string or object.
     */
    static createFrom($$source: any = {}): Version {
        const $$createField5_0 = $$createType4;
        const $$createField6_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("parents" in $$parsedSource) {
            $$parsedSource["parents"] = $$createField5_0($$parsedSource["parents"]);
        }
        if ("branches" in $$parsedSource) {
            $$parsedSource["branches"] = $$createField6_0($$parsedSource["branches"]);
        }
        return new Version($$parsedSource as Partial<Version>);
    }
}

// Private type creation functions
const $$createType0 = MemberBackup.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Version.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = TrackWeight.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Array($Create.Any);
const $$createType8 = TeamSummary.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = TeamProject.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = PreuploadFile.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $Create.Array($$createType2);
const $$createType15 = Change.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = Conflict.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = RulesInfo.createFrom;
const $$createType20 = backup$0.PlanProject.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = remote$0.Storage.createFrom;
const $$createType23 = $Create.Nullable($$createType22);
const $$createType24 = profile$0.PresetEntry.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = RuleItem.createFrom;
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = RuleSuggestion.createFrom;
const $$createType29 = $Create.Array($$createType28);
const $$createType30 = PresetOption.createFrom;
const $$createType31 = $Create.Array($$createType30);
const $$createType32 = profile$0.Applied.createFrom;
const $$createType33 = $Create.Array($$createType32);
const $$createType34 = als$0.Overview.createFrom;
const $$createType35 = $Create.Nullable($$createType34);
const $$createType36 = SetTrackChange.createFrom;
const $$createType37 = $Create.Array($$createType36);
const $$createType38 = project$0.TrackEdit.createFrom;
const $$createType39 = $Create.Array($$createType38);
const $$createType40 = Branch.createFrom;
const $$createType41 = $Create.Array($$createType40);
const $$createType42 = remote$0.Capabilities.createFrom;
const $$createType43 = textdiff$0.Hunk.createFrom;
const $$createType44 = $Create.Array($$createType43);
const $$createType45 = TakeBack.createFrom;
const $$createType46 = VerifyProblem.createFrom;
const $$createType47 = $Create.Array($$createType46);
