// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * PlanProject is a project the restore brings back whole.
 */
export class PlanProject {
    "id": string;
    "name": string;
    "versions": number;

    /** Creates a new PlanProject instance. */
    constructor($$source: Partial<PlanProject> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("versions" in $$source)) {
            this["versions"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlanProject instance from a string or object.
     */
    static createFrom($$source: any = {}): PlanProject {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlanProject($$parsedSource as Partial<PlanProject>);
    }
}
